# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstPageUi.ui'
#
# Created: Wed Jan  5 21:23:25 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 642)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.horizontalLayoutWidget = QtGui.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.groupBox = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(541, 0))
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 30, 80, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.groupBox_6, 0, 2, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 50, 80, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_9.setObjectName("groupBox_9")
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_10.setGeometry(QtCore.QRect(60, 50, 80, 25))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.groupBox_9, 1, 1, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 30, 80, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.groupBox_8, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(7)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.newAnButton = QtGui.QPushButton(self.tab_2)
        self.newAnButton.setObjectName("newAnButton")
        self.verticalLayout_2.addWidget(self.newAnButton)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget = QtGui.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 130, 571, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_10 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_10.setObjectName("groupBox_10")
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_10)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 40, 80, 25))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_7.addWidget(self.groupBox_10, 1, 0, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_11.setObjectName("groupBox_11")
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_12.setGeometry(QtCore.QRect(80, 40, 80, 25))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_7.addWidget(self.groupBox_11, 1, 1, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_12.setObjectName("groupBox_12")
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_12)
        self.pushButton_13.setGeometry(QtCore.QRect(100, 50, 80, 25))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_7.addWidget(self.groupBox_12, 2, 0, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_13.setObjectName("groupBox_13")
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_13)
        self.pushButton_14.setGeometry(QtCore.QRect(100, 30, 80, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_7.addWidget(self.groupBox_13, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(397, 159))
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 883, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionWeb = QtGui.QAction(MainWindow)
        self.actionWeb.setCheckable(True)
        self.actionWeb.setObjectName("actionWeb")
        self.action = QtGui.QAction(MainWindow)
        self.action.setCheckable(True)
        self.action.setObjectName("action")
        self.actionLoop = QtGui.QAction(MainWindow)
        self.actionLoop.setCheckable(True)
        self.actionLoop.setObjectName("actionLoop")
        self.actionOngsuiv = QtGui.QAction(MainWindow)
        self.actionOngsuiv.setObjectName("actionOngsuiv")
        self.actionOngprec = QtGui.QAction(MainWindow)
        self.actionOngprec.setObjectName("actionOngprec")
        self.toolBar.addAction(self.actionOngprec)
        self.toolBar.addAction(self.actionOngsuiv)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Genetic data", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Historical model", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Simulated data sets", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Reference Table", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "type", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "priority", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "status", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "results", None, QtGui.QApplication.UnicodeUTF8))
        self.newAnButton.setText(QtGui.QApplication.translate("MainWindow", "Define new analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Analyses", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Projet 2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "Genetic data", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Historical model", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("MainWindow", "Simulated data sets", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Projet 1", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWeb.setText(QtGui.QApplication.translate("MainWindow", "activer web", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWeb.setToolTip(QtGui.QApplication.translate("MainWindow", "obvious", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "plap", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setToolTip(QtGui.QApplication.translate("MainWindow", "hohoho", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoop.setText(QtGui.QApplication.translate("MainWindow", "loop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoop.setToolTip(QtGui.QApplication.translate("MainWindow", "c\'est la vie!", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoop.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOngsuiv.setText(QtGui.QApplication.translate("MainWindow", "ongsuiv", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOngsuiv.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOngprec.setText(QtGui.QApplication.translate("MainWindow", "ongprec", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOngprec.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+PgUp", None, QtGui.QApplication.UnicodeUTF8))

