#!/bin/bash
# CBGP

#if [ -f /usr/bin/update-menus ]; then
#    update-menus
#fi
set -e
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
    update-menus
fi

chown -R 0:0 /usr/local/bin/diyabc-git*
chown -R 0:0 /usr/local/share/applications/*diaybc* 
chown -R 0:0 /usr/local/share/menu/*diyabc*

echo "


****************  WARNING  *****************
***                                      *** 
***  run diyabc-git-init in a terminal   ***
***  in order to initialize your DIYABC  ***
***  local copy from CBGP git server     ***
***                                      ***
********************************************


"
echo DIYABC-git installed

