# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/preferences.ui'
#
# Created: Mon Feb 14 12:03:11 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1000, 750)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 750))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_56 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.addrEdit = QtGui.QLineEdit(self.tab)
        self.addrEdit.setObjectName("addrEdit")
        self.gridLayout.addWidget(self.addrEdit, 1, 0, 1, 1)
        self.portEdit = QtGui.QLineEdit(self.tab)
        self.portEdit.setObjectName("portEdit")
        self.gridLayout.addWidget(self.portEdit, 1, 1, 1, 1)
        self.connectButton = QtGui.QPushButton(self.tab)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 1, 2, 1, 1)
        self.verticalLayout_56.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_57 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.setMutSeqLabel_2 = QtGui.QLabel(self.tab_4)
        self.setMutSeqLabel_2.setMinimumSize(QtCore.QSize(0, 25))
        self.setMutSeqLabel_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setMutSeqLabel_2.setFont(font)
        self.setMutSeqLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.setMutSeqLabel_2.setObjectName("setMutSeqLabel_2")
        self.verticalLayout_57.addWidget(self.setMutSeqLabel_2)
        self.frame_11 = QtGui.QFrame(self.tab_4)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 21))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 21))
        self.frame_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.frame_11)
        self.horizontalLayout_27.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.groupBox_14 = QtGui.QGroupBox(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setMinimumSize(QtCore.QSize(140, 20))
        self.groupBox_14.setMaximumSize(QtCore.QSize(140, 20))
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_28.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_64 = QtGui.QLabel(self.groupBox_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setMinimumSize(QtCore.QSize(140, 0))
        self.label_64.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_28.addWidget(self.label_64)
        self.horizontalLayout_27.addWidget(self.groupBox_14)
        self.groupBox_15 = QtGui.QGroupBox(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_15.sizePolicy().hasHeightForWidth())
        self.groupBox_15.setSizePolicy(sizePolicy)
        self.groupBox_15.setMinimumSize(QtCore.QSize(290, 20))
        self.groupBox_15.setMaximumSize(QtCore.QSize(290, 20))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_29.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_67 = QtGui.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_29.addWidget(self.label_67)
        self.label_68 = QtGui.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_68.setFont(font)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_29.addWidget(self.label_68)
        self.label_69 = QtGui.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_69.setFont(font)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_29.addWidget(self.label_69)
        self.label_70 = QtGui.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_29.addWidget(self.label_70)
        self.horizontalLayout_27.addWidget(self.groupBox_15)
        self.groupBox_16 = QtGui.QGroupBox(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_16.sizePolicy().hasHeightForWidth())
        self.groupBox_16.setSizePolicy(sizePolicy)
        self.groupBox_16.setMinimumSize(QtCore.QSize(0, 20))
        self.groupBox_16.setMaximumSize(QtCore.QSize(16777215, 20))
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_30.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_71 = QtGui.QLabel(self.groupBox_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_71.sizePolicy().hasHeightForWidth())
        self.label_71.setSizePolicy(sizePolicy)
        self.label_71.setMinimumSize(QtCore.QSize(80, 0))
        self.label_71.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_71.setFont(font)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_30.addWidget(self.label_71)
        self.label_72 = QtGui.QLabel(self.groupBox_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setMinimumSize(QtCore.QSize(80, 0))
        self.label_72.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_30.addWidget(self.label_72)
        self.label_73 = QtGui.QLabel(self.groupBox_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setMinimumSize(QtCore.QSize(80, 0))
        self.label_73.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_73.setFont(font)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_30.addWidget(self.label_73)
        self.label_74 = QtGui.QLabel(self.groupBox_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setMinimumSize(QtCore.QSize(80, 0))
        self.label_74.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_74.setFont(font)
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_30.addWidget(self.label_74)
        self.horizontalLayout_27.addWidget(self.groupBox_16)
        self.verticalLayout_57.addWidget(self.frame_11)
        self.frame_12 = QtGui.QFrame(self.tab_4)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_12.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.frame_12)
        self.horizontalLayout_31.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.groupBox_17 = QtGui.QGroupBox(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_17.sizePolicy().hasHeightForWidth())
        self.groupBox_17.setSizePolicy(sizePolicy)
        self.groupBox_17.setMinimumSize(QtCore.QSize(140, 40))
        self.groupBox_17.setMaximumSize(QtCore.QSize(140, 40))
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_32.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_75 = QtGui.QLabel(self.groupBox_17)
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_32.addWidget(self.label_75)
        self.horizontalLayout_31.addWidget(self.groupBox_17)
        self.groupBox_18 = QtGui.QGroupBox(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_18.sizePolicy().hasHeightForWidth())
        self.groupBox_18.setSizePolicy(sizePolicy)
        self.groupBox_18.setMinimumSize(QtCore.QSize(290, 40))
        self.groupBox_18.setMaximumSize(QtCore.QSize(290, 40))
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.groupBox_18)
        self.horizontalLayout_33.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.NUNRadio = QtGui.QRadioButton(self.groupBox_18)
        self.NUNRadio.setText("")
        self.NUNRadio.setChecked(True)
        self.NUNRadio.setObjectName("NUNRadio")
        self.horizontalLayout_33.addWidget(self.NUNRadio)
        self.NLURadio = QtGui.QRadioButton(self.groupBox_18)
        self.NLURadio.setText("")
        self.NLURadio.setObjectName("NLURadio")
        self.horizontalLayout_33.addWidget(self.NLURadio)
        self.NNORadio = QtGui.QRadioButton(self.groupBox_18)
        self.NNORadio.setText("")
        self.NNORadio.setObjectName("NNORadio")
        self.horizontalLayout_33.addWidget(self.NNORadio)
        self.NLNRadio = QtGui.QRadioButton(self.groupBox_18)
        self.NLNRadio.setText("")
        self.NLNRadio.setObjectName("NLNRadio")
        self.horizontalLayout_33.addWidget(self.NLNRadio)
        self.horizontalLayout_31.addWidget(self.groupBox_18)
        self.groupBox_19 = QtGui.QGroupBox(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_19.sizePolicy().hasHeightForWidth())
        self.groupBox_19.setSizePolicy(sizePolicy)
        self.groupBox_19.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_19.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.horizontalLayout_34 = QtGui.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_34.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.NminEdit = QtGui.QLineEdit(self.groupBox_19)
        self.NminEdit.setObjectName("NminEdit")
        self.horizontalLayout_34.addWidget(self.NminEdit)
        self.NmaxEdit = QtGui.QLineEdit(self.groupBox_19)
        self.NmaxEdit.setObjectName("NmaxEdit")
        self.horizontalLayout_34.addWidget(self.NmaxEdit)
        self.NmeanEdit = QtGui.QLineEdit(self.groupBox_19)
        self.NmeanEdit.setObjectName("NmeanEdit")
        self.horizontalLayout_34.addWidget(self.NmeanEdit)
        self.NstdevEdit = QtGui.QLineEdit(self.groupBox_19)
        self.NstdevEdit.setObjectName("NstdevEdit")
        self.horizontalLayout_34.addWidget(self.NstdevEdit)
        self.horizontalLayout_31.addWidget(self.groupBox_19)
        self.verticalLayout_57.addWidget(self.frame_12)
        self.frame_13 = QtGui.QFrame(self.tab_4)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_35 = QtGui.QHBoxLayout(self.frame_13)
        self.horizontalLayout_35.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.groupBox_20 = QtGui.QGroupBox(self.frame_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_20.sizePolicy().hasHeightForWidth())
        self.groupBox_20.setSizePolicy(sizePolicy)
        self.groupBox_20.setMinimumSize(QtCore.QSize(140, 40))
        self.groupBox_20.setMaximumSize(QtCore.QSize(140, 40))
        self.groupBox_20.setTitle("")
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayout_36 = QtGui.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_36.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_77 = QtGui.QLabel(self.groupBox_20)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_36.addWidget(self.label_77)
        self.horizontalLayout_35.addWidget(self.groupBox_20)
        self.groupBox_21 = QtGui.QGroupBox(self.frame_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_21.sizePolicy().hasHeightForWidth())
        self.groupBox_21.setSizePolicy(sizePolicy)
        self.groupBox_21.setMinimumSize(QtCore.QSize(290, 40))
        self.groupBox_21.setMaximumSize(QtCore.QSize(290, 40))
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.horizontalLayout_37 = QtGui.QHBoxLayout(self.groupBox_21)
        self.horizontalLayout_37.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.TUNRadio = QtGui.QRadioButton(self.groupBox_21)
        self.TUNRadio.setText("")
        self.TUNRadio.setChecked(True)
        self.TUNRadio.setObjectName("TUNRadio")
        self.horizontalLayout_37.addWidget(self.TUNRadio)
        self.TLURadio = QtGui.QRadioButton(self.groupBox_21)
        self.TLURadio.setText("")
        self.TLURadio.setObjectName("TLURadio")
        self.horizontalLayout_37.addWidget(self.TLURadio)
        self.TNORadio = QtGui.QRadioButton(self.groupBox_21)
        self.TNORadio.setText("")
        self.TNORadio.setObjectName("TNORadio")
        self.horizontalLayout_37.addWidget(self.TNORadio)
        self.TLNRadio = QtGui.QRadioButton(self.groupBox_21)
        self.TLNRadio.setText("")
        self.TLNRadio.setObjectName("TLNRadio")
        self.horizontalLayout_37.addWidget(self.TLNRadio)
        self.horizontalLayout_35.addWidget(self.groupBox_21)
        self.groupBox_22 = QtGui.QGroupBox(self.frame_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_22.sizePolicy().hasHeightForWidth())
        self.groupBox_22.setSizePolicy(sizePolicy)
        self.groupBox_22.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_22.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.groupBox_22)
        self.horizontalLayout_38.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.TminEdit = QtGui.QLineEdit(self.groupBox_22)
        self.TminEdit.setObjectName("TminEdit")
        self.horizontalLayout_38.addWidget(self.TminEdit)
        self.TmaxEdit = QtGui.QLineEdit(self.groupBox_22)
        self.TmaxEdit.setObjectName("TmaxEdit")
        self.horizontalLayout_38.addWidget(self.TmaxEdit)
        self.TmeanEdit = QtGui.QLineEdit(self.groupBox_22)
        self.TmeanEdit.setObjectName("TmeanEdit")
        self.horizontalLayout_38.addWidget(self.TmeanEdit)
        self.TstdevEdit = QtGui.QLineEdit(self.groupBox_22)
        self.TstdevEdit.setObjectName("TstdevEdit")
        self.horizontalLayout_38.addWidget(self.TstdevEdit)
        self.horizontalLayout_35.addWidget(self.groupBox_22)
        self.verticalLayout_57.addWidget(self.frame_13)
        self.frame_14 = QtGui.QFrame(self.tab_4)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_39 = QtGui.QHBoxLayout(self.frame_14)
        self.horizontalLayout_39.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.groupBox_23 = QtGui.QGroupBox(self.frame_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_23.sizePolicy().hasHeightForWidth())
        self.groupBox_23.setSizePolicy(sizePolicy)
        self.groupBox_23.setMinimumSize(QtCore.QSize(140, 40))
        self.groupBox_23.setMaximumSize(QtCore.QSize(140, 40))
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.horizontalLayout_40 = QtGui.QHBoxLayout(self.groupBox_23)
        self.horizontalLayout_40.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_76 = QtGui.QLabel(self.groupBox_23)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_40.addWidget(self.label_76)
        self.horizontalLayout_39.addWidget(self.groupBox_23)
        self.groupBox_24 = QtGui.QGroupBox(self.frame_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_24.sizePolicy().hasHeightForWidth())
        self.groupBox_24.setSizePolicy(sizePolicy)
        self.groupBox_24.setMinimumSize(QtCore.QSize(290, 40))
        self.groupBox_24.setMaximumSize(QtCore.QSize(290, 40))
        self.groupBox_24.setTitle("")
        self.groupBox_24.setObjectName("groupBox_24")
        self.horizontalLayout_41 = QtGui.QHBoxLayout(self.groupBox_24)
        self.horizontalLayout_41.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.AUNRadio = QtGui.QRadioButton(self.groupBox_24)
        self.AUNRadio.setText("")
        self.AUNRadio.setChecked(True)
        self.AUNRadio.setObjectName("AUNRadio")
        self.horizontalLayout_41.addWidget(self.AUNRadio)
        self.ALURadio = QtGui.QRadioButton(self.groupBox_24)
        self.ALURadio.setText("")
        self.ALURadio.setObjectName("ALURadio")
        self.horizontalLayout_41.addWidget(self.ALURadio)
        self.ANORadio = QtGui.QRadioButton(self.groupBox_24)
        self.ANORadio.setText("")
        self.ANORadio.setObjectName("ANORadio")
        self.horizontalLayout_41.addWidget(self.ANORadio)
        self.ALNRadio = QtGui.QRadioButton(self.groupBox_24)
        self.ALNRadio.setText("")
        self.ALNRadio.setObjectName("ALNRadio")
        self.horizontalLayout_41.addWidget(self.ALNRadio)
        self.horizontalLayout_39.addWidget(self.groupBox_24)
        self.groupBox_25 = QtGui.QGroupBox(self.frame_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_25.sizePolicy().hasHeightForWidth())
        self.groupBox_25.setSizePolicy(sizePolicy)
        self.groupBox_25.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_25.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_25.setTitle("")
        self.groupBox_25.setObjectName("groupBox_25")
        self.horizontalLayout_42 = QtGui.QHBoxLayout(self.groupBox_25)
        self.horizontalLayout_42.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.AminEdit = QtGui.QLineEdit(self.groupBox_25)
        self.AminEdit.setObjectName("AminEdit")
        self.horizontalLayout_42.addWidget(self.AminEdit)
        self.AmaxEdit = QtGui.QLineEdit(self.groupBox_25)
        self.AmaxEdit.setObjectName("AmaxEdit")
        self.horizontalLayout_42.addWidget(self.AmaxEdit)
        self.AmeanEdit = QtGui.QLineEdit(self.groupBox_25)
        self.AmeanEdit.setObjectName("AmeanEdit")
        self.horizontalLayout_42.addWidget(self.AmeanEdit)
        self.AstdevEdit = QtGui.QLineEdit(self.groupBox_25)
        self.AstdevEdit.setObjectName("AstdevEdit")
        self.horizontalLayout_42.addWidget(self.AstdevEdit)
        self.horizontalLayout_39.addWidget(self.groupBox_25)
        self.verticalLayout_57.addWidget(self.frame_14)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame_10 = QtGui.QFrame(self.centralwidget)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.frame_10)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.cancelButton = QtGui.QPushButton(self.frame_10)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_26.addWidget(self.cancelButton)
        self.saveButton = QtGui.QPushButton(self.frame_10)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_26.addWidget(self.saveButton)
        self.verticalLayout.addWidget(self.frame_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Address of the server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.setMutSeqLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Default values of historical model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Log-uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Log-normal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("MainWindow", "maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("MainWindow", "mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("MainWindow", "st-deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("MainWindow", "Type N", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(QtGui.QApplication.translate("MainWindow", "Type T", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(QtGui.QApplication.translate("MainWindow", "Type A", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))

