# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/Project.ui'
#
# Created: Thu Feb 10 15:03:46 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(975, 810)
        self.tabRefTable = QtGui.QWidget()
        self.tabRefTable.setObjectName("tabRefTable")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabRefTable)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.refTableStack = QtGui.QStackedWidget(self.tabRefTable)
        self.refTableStack.setObjectName("refTableStack")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame = QtGui.QFrame(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.gridLayout_4 = QtGui.QGridLayout(self.horizontalFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.projNameLabel = QtGui.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.projNameLabel.setFont(font)
        self.projNameLabel.setObjectName("projNameLabel")
        self.gridLayout_4.addWidget(self.projNameLabel, 0, 0, 1, 1)
        self.projNameLabelValue = QtGui.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.projNameLabelValue.setFont(font)
        self.projNameLabelValue.setFrameShape(QtGui.QFrame.Box)
        self.projNameLabelValue.setAlignment(QtCore.Qt.AlignCenter)
        self.projNameLabelValue.setObjectName("projNameLabelValue")
        self.gridLayout_4.addWidget(self.projNameLabelValue, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.horizontalFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.browseDataFileButton = QtGui.QPushButton(self.horizontalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseDataFileButton.sizePolicy().hasHeightForWidth())
        self.browseDataFileButton.setSizePolicy(sizePolicy)
        self.browseDataFileButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.browseDataFileButton.setObjectName("browseDataFileButton")
        self.gridLayout_4.addWidget(self.browseDataFileButton, 1, 1, 1, 1)
        self.dataFileEdit = QtGui.QLineEdit(self.horizontalFrame)
        self.dataFileEdit.setObjectName("dataFileEdit")
        self.gridLayout_4.addWidget(self.dataFileEdit, 1, 2, 1, 1)
        self.dirEdit = QtGui.QLineEdit(self.horizontalFrame)
        self.dirEdit.setObjectName("dirEdit")
        self.gridLayout_4.addWidget(self.dirEdit, 0, 5, 1, 1)
        self.browseDirButton = QtGui.QPushButton(self.horizontalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseDirButton.sizePolicy().hasHeightForWidth())
        self.browseDirButton.setSizePolicy(sizePolicy)
        self.browseDirButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.browseDirButton.setObjectName("browseDirButton")
        self.gridLayout_4.addWidget(self.browseDirButton, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.horizontalFrame)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 3, 1, 1)
        self.dataFileInfoLabel = QtGui.QLabel(self.horizontalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataFileInfoLabel.sizePolicy().hasHeightForWidth())
        self.dataFileInfoLabel.setSizePolicy(sizePolicy)
        self.dataFileInfoLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.dataFileInfoLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.dataFileInfoLabel.setText("")
        self.dataFileInfoLabel.setObjectName("dataFileInfoLabel")
        self.gridLayout_4.addWidget(self.dataFileInfoLabel, 1, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.horizontalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.groupBox = QtGui.QGroupBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(541, 0))
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 25))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 0, 0, 1, 1)
        self.setHistoricalButton = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setHistoricalButton.sizePolicy().hasHeightForWidth())
        self.setHistoricalButton.setSizePolicy(sizePolicy)
        self.setHistoricalButton.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.setHistoricalButton.setFont(font)
        self.setHistoricalButton.setIconSize(QtCore.QSize(50, 50))
        self.setHistoricalButton.setObjectName("setHistoricalButton")
        self.gridLayout_10.addWidget(self.setHistoricalButton, 2, 0, 1, 1)
        self.frame = QtGui.QFrame(self.groupBox_7)
        self.frame.setFrameShape(QtGui.QFrame.HLine)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_10.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.groupBox_7)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nbScLabel = QtGui.QLabel(self.frame_5)
        self.nbScLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nbScLabel.setObjectName("nbScLabel")
        self.horizontalLayout.addWidget(self.nbScLabel)
        self.nbParamLabel = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbParamLabel.sizePolicy().hasHeightForWidth())
        self.nbParamLabel.setSizePolicy(sizePolicy)
        self.nbParamLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nbParamLabel.setObjectName("nbParamLabel")
        self.horizontalLayout.addWidget(self.nbParamLabel)
        self.gridLayout_10.addWidget(self.frame_5, 3, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setAutoFillBackground(False)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 25))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.groupBox_6)
        self.frame_2.setFrameShape(QtGui.QFrame.HLine)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_8.addWidget(self.frame_2, 1, 0, 1, 1)
        self.setGeneticButton = QtGui.QPushButton(self.groupBox_6)
        self.setGeneticButton.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.setGeneticButton.setFont(font)
        self.setGeneticButton.setIconSize(QtCore.QSize(50, 50))
        self.setGeneticButton.setObjectName("setGeneticButton")
        self.gridLayout_8.addWidget(self.setGeneticButton, 2, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.groupBox_6)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.nbMicrosatLabel = QtGui.QLabel(self.frame_6)
        self.nbMicrosatLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nbMicrosatLabel.setObjectName("nbMicrosatLabel")
        self.gridLayout_5.addWidget(self.nbMicrosatLabel, 0, 0, 1, 1)
        self.nbSequencesLabel = QtGui.QLabel(self.frame_6)
        self.nbSequencesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nbSequencesLabel.setObjectName("nbSequencesLabel")
        self.gridLayout_5.addWidget(self.nbSequencesLabel, 0, 1, 1, 1)
        self.nbGroupLabel = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbGroupLabel.sizePolicy().hasHeightForWidth())
        self.nbGroupLabel.setSizePolicy(sizePolicy)
        self.nbGroupLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.nbGroupLabel.setBaseSize(QtCore.QSize(0, 0))
        self.nbGroupLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nbGroupLabel.setObjectName("nbGroupLabel")
        self.gridLayout_5.addWidget(self.nbGroupLabel, 1, 0, 1, 1)
        self.nbSumStatsLabel = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbSumStatsLabel.sizePolicy().hasHeightForWidth())
        self.nbSumStatsLabel.setSizePolicy(sizePolicy)
        self.nbSumStatsLabel.setMinimumSize(QtCore.QSize(0, 80))
        self.nbSumStatsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nbSumStatsLabel.setObjectName("nbSumStatsLabel")
        self.gridLayout_5.addWidget(self.nbSumStatsLabel, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.frame_6, 3, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_11.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_20 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 0, 0, 1, 1)
        self.runButton = QtGui.QPushButton(self.groupBox_8)
        self.runButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.gridLayout_11.addWidget(self.runButton, 4, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.groupBox_8)
        self.frame_4.setFrameShape(QtGui.QFrame.HLine)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_11.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_8 = QtGui.QFrame(self.groupBox_8)
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtGui.QLabel(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 40))
        self.label_6.setMaximumSize(QtCore.QSize(200, 40))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 40))
        self.label_8.setMaximumSize(QtCore.QSize(200, 40))
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 40))
        self.label_9.setMaximumSize(QtCore.QSize(200, 40))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit.setMaximumSize(QtCore.QSize(30, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 3, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(120, 26))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 2, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(120, 26))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 4, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_11.addWidget(self.frame_8, 2, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 25))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_11.addWidget(self.progressBar, 3, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.verticalLayout.addWidget(self.groupBox)
        self.refTableStack.addWidget(self.page)
        self.verticalLayout_5.addWidget(self.refTableStack)
        TabWidget.addTab(self.tabRefTable, "")
        self.tabAnalyses = QtGui.QWidget()
        self.tabAnalyses.setObjectName("tabAnalyses")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabAnalyses)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtGui.QTableWidget(self.tabAnalyses)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.newAnButton = QtGui.QPushButton(self.tabAnalyses)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newAnButton.sizePolicy().hasHeightForWidth())
        self.newAnButton.setSizePolicy(sizePolicy)
        self.newAnButton.setMinimumSize(QtCore.QSize(581, 101))
        self.newAnButton.setBaseSize(QtCore.QSize(581, 101))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.newAnButton.setFont(font)
        self.newAnButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newAnButton.setObjectName("newAnButton")
        self.verticalLayout_2.addWidget(self.newAnButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        TabWidget.addTab(self.tabAnalyses, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(QtGui.QApplication.translate("TabWidget", "TabWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.projNameLabel.setText(QtGui.QApplication.translate("TabWidget", "Project name :", None, QtGui.QApplication.UnicodeUTF8))
        self.projNameLabelValue.setText(QtGui.QApplication.translate("TabWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TabWidget", "Data file : ", None, QtGui.QApplication.UnicodeUTF8))
        self.browseDataFileButton.setText(QtGui.QApplication.translate("TabWidget", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.browseDirButton.setText(QtGui.QApplication.translate("TabWidget", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TabWidget", "Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TabWidget", "Data file info :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("TabWidget", "Historical model", None, QtGui.QApplication.UnicodeUTF8))
        self.setHistoricalButton.setToolTip(QtGui.QApplication.translate("TabWidget", "(Alt+h)", None, QtGui.QApplication.UnicodeUTF8))
        self.setHistoricalButton.setText(QtGui.QApplication.translate("TabWidget", "            Set", None, QtGui.QApplication.UnicodeUTF8))
        self.setHistoricalButton.setShortcut(QtGui.QApplication.translate("TabWidget", "Alt+H", None, QtGui.QApplication.UnicodeUTF8))
        self.nbScLabel.setText(QtGui.QApplication.translate("TabWidget", "X scenarios", None, QtGui.QApplication.UnicodeUTF8))
        self.nbParamLabel.setText(QtGui.QApplication.translate("TabWidget", "X parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("TabWidget", "Genetic data and Summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.setGeneticButton.setToolTip(QtGui.QApplication.translate("TabWidget", "(Alt+g)", None, QtGui.QApplication.UnicodeUTF8))
        self.setGeneticButton.setText(QtGui.QApplication.translate("TabWidget", "            Set", None, QtGui.QApplication.UnicodeUTF8))
        self.setGeneticButton.setShortcut(QtGui.QApplication.translate("TabWidget", "Alt+G", None, QtGui.QApplication.UnicodeUTF8))
        self.nbMicrosatLabel.setText(QtGui.QApplication.translate("TabWidget", "X microsatellite loci", None, QtGui.QApplication.UnicodeUTF8))
        self.nbSequencesLabel.setText(QtGui.QApplication.translate("TabWidget", "X DNA sequence loci", None, QtGui.QApplication.UnicodeUTF8))
        self.nbGroupLabel.setText(QtGui.QApplication.translate("TabWidget", "X locus groups", None, QtGui.QApplication.UnicodeUTF8))
        self.nbSumStatsLabel.setText(QtGui.QApplication.translate("TabWidget", "X summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("TabWidget", "Simulated data sets", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("TabWidget", "Run computations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TabWidget", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TabWidget", "Number of simulated data sets in the reference table", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TabWidget", "Required number of simulated data sets", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.tabRefTable), QtGui.QApplication.translate("TabWidget", "Reference table", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("TabWidget", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("TabWidget", "type", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("TabWidget", "parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("TabWidget", "priority", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("TabWidget", "status", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("TabWidget", "results", None, QtGui.QApplication.UnicodeUTF8))
        self.newAnButton.setText(QtGui.QApplication.translate("TabWidget", "Define new analysis", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.tabAnalyses), QtGui.QApplication.translate("TabWidget", "Analyses", None, QtGui.QApplication.UnicodeUTF8))

