# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/setMutationModelSequences.ui'
#
# Created: Wed Jan 26 11:12:42 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(955, 685)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_28 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_6 = QtGui.QFrame(Frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.exitButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_9.addWidget(self.exitButton)
        self.clearButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_9.addWidget(self.clearButton)
        self.okButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_9.addWidget(self.okButton)
        self.verticalLayout_28.addWidget(self.frame_6)
        self.setMutSeqLabel = QtGui.QLabel(Frame)
        self.setMutSeqLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setMutSeqLabel.setFont(font)
        self.setMutSeqLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.setMutSeqLabel.setObjectName("setMutSeqLabel")
        self.verticalLayout_28.addWidget(self.setMutSeqLabel)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame = QtGui.QFrame(Frame)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.firstFrame = QtGui.QFrame(self.frame)
        self.firstFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.firstFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.firstFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.firstFrame.setObjectName("firstFrame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.firstFrame)
        self.horizontalLayout_7.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtGui.QLabel(self.firstFrame)
        self.label_18.setMinimumSize(QtCore.QSize(130, 0))
        self.label_18.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.groupBox_4 = QtGui.QGroupBox(self.firstFrame)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_8.addWidget(self.radioButton_10)
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setChecked(False)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_8.addWidget(self.radioButton_11)
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_8.addWidget(self.radioButton_12)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_19 = QtGui.QLabel(self.firstFrame)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_14.addWidget(self.label_19)
        self.lineEdit_13 = QtGui.QLineEdit(self.firstFrame)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_14.addWidget(self.lineEdit_13)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_20 = QtGui.QLabel(self.firstFrame)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_15.addWidget(self.label_20)
        self.lineEdit_14 = QtGui.QLineEdit(self.firstFrame)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_15.addWidget(self.lineEdit_14)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_21 = QtGui.QLabel(self.firstFrame)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_16.addWidget(self.label_21)
        self.lineEdit_15 = QtGui.QLineEdit(self.firstFrame)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_16.addWidget(self.lineEdit_15)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_22 = QtGui.QLabel(self.firstFrame)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_17.addWidget(self.label_22)
        self.lineEdit_16 = QtGui.QLineEdit(self.firstFrame)
        self.lineEdit_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_17.addWidget(self.lineEdit_16)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.verticalLayout_26.addWidget(self.firstFrame)
        self.secondFrame = QtGui.QFrame(self.frame)
        self.secondFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.secondFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.secondFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.secondFrame.setObjectName("secondFrame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.secondFrame)
        self.horizontalLayout_5.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtGui.QLabel(self.secondFrame)
        self.label_13.setMinimumSize(QtCore.QSize(130, 0))
        self.label_13.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.groupBox_3 = QtGui.QGroupBox(self.secondFrame)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_6.addWidget(self.radioButton_9)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_14 = QtGui.QLabel(self.secondFrame)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.lineEdit_9 = QtGui.QLineEdit(self.secondFrame)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_10.addWidget(self.lineEdit_9)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_15 = QtGui.QLabel(self.secondFrame)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15)
        self.lineEdit_10 = QtGui.QLineEdit(self.secondFrame)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_11.addWidget(self.lineEdit_10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtGui.QLabel(self.secondFrame)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.lineEdit_11 = QtGui.QLineEdit(self.secondFrame)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_12.addWidget(self.lineEdit_11)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_17 = QtGui.QLabel(self.secondFrame)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        self.lineEdit_12 = QtGui.QLineEdit(self.secondFrame)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_13.addWidget(self.lineEdit_12)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_26.addWidget(self.secondFrame)
        self.thirdFrame = QtGui.QFrame(self.frame)
        self.thirdFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.thirdFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.thirdFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.thirdFrame.setObjectName("thirdFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.thirdFrame)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.thirdFrame)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        self.label_3.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.groupBox = QtGui.QGroupBox(self.thirdFrame)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.thirdFrame)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit = QtGui.QLineEdit(self.thirdFrame)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(self.thirdFrame)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_2 = QtGui.QLineEdit(self.thirdFrame)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtGui.QLabel(self.thirdFrame)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lineEdit_3 = QtGui.QLineEdit(self.thirdFrame)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtGui.QLabel(self.thirdFrame)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.lineEdit_4 = QtGui.QLineEdit(self.thirdFrame)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_26.addWidget(self.thirdFrame)
        self.fourthFrame = QtGui.QFrame(self.frame)
        self.fourthFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fourthFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fourthFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fourthFrame.setObjectName("fourthFrame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.fourthFrame)
        self.horizontalLayout_3.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtGui.QLabel(self.fourthFrame)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        self.label_8.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.groupBox_2 = QtGui.QGroupBox(self.fourthFrame)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_4.addWidget(self.radioButton_6)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtGui.QLabel(self.fourthFrame)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.lineEdit_5 = QtGui.QLineEdit(self.fourthFrame)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtGui.QLabel(self.fourthFrame)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.lineEdit_6 = QtGui.QLineEdit(self.fourthFrame)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_7.addWidget(self.lineEdit_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtGui.QLabel(self.fourthFrame)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.lineEdit_7 = QtGui.QLineEdit(self.fourthFrame)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_8.addWidget(self.lineEdit_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtGui.QLabel(self.fourthFrame)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.lineEdit_8 = QtGui.QLineEdit(self.fourthFrame)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_9.addWidget(self.lineEdit_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_26.addWidget(self.fourthFrame)
        self.fifthFrame = QtGui.QFrame(self.frame)
        self.fifthFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fifthFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fifthFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fifthFrame.setObjectName("fifthFrame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.fifthFrame)
        self.horizontalLayout_10.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_23 = QtGui.QLabel(self.fifthFrame)
        self.label_23.setMinimumSize(QtCore.QSize(130, 0))
        self.label_23.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.groupBox_5 = QtGui.QGroupBox(self.fifthFrame)
        self.groupBox_5.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_13.setFont(font)
        self.radioButton_13.setChecked(True)
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_11.addWidget(self.radioButton_13)
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setChecked(False)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_11.addWidget(self.radioButton_14)
        self.radioButton_15 = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_15.setFont(font)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_11.addWidget(self.radioButton_15)
        self.horizontalLayout_10.addWidget(self.groupBox_5)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_24 = QtGui.QLabel(self.fifthFrame)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_18.addWidget(self.label_24)
        self.lineEdit_17 = QtGui.QLineEdit(self.fifthFrame)
        self.lineEdit_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_18.addWidget(self.lineEdit_17)
        self.horizontalLayout_10.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_25 = QtGui.QLabel(self.fifthFrame)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_19.addWidget(self.label_25)
        self.lineEdit_18 = QtGui.QLineEdit(self.fifthFrame)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_19.addWidget(self.lineEdit_18)
        self.horizontalLayout_10.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_26 = QtGui.QLabel(self.fifthFrame)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_20.addWidget(self.label_26)
        self.lineEdit_19 = QtGui.QLineEdit(self.fifthFrame)
        self.lineEdit_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_20.addWidget(self.lineEdit_19)
        self.horizontalLayout_10.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_27 = QtGui.QLabel(self.fifthFrame)
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_21.addWidget(self.label_27)
        self.lineEdit_20 = QtGui.QLineEdit(self.fifthFrame)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_21.addWidget(self.lineEdit_20)
        self.horizontalLayout_10.addLayout(self.verticalLayout_21)
        self.verticalLayout_26.addWidget(self.fifthFrame)
        self.sixthFrame = QtGui.QFrame(self.frame)
        self.sixthFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.sixthFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sixthFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sixthFrame.setObjectName("sixthFrame")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.sixthFrame)
        self.horizontalLayout_12.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_28 = QtGui.QLabel(self.sixthFrame)
        self.label_28.setMinimumSize(QtCore.QSize(130, 0))
        self.label_28.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        self.groupBox_6 = QtGui.QGroupBox(self.sixthFrame)
        self.groupBox_6.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_13.setSpacing(1)
        self.horizontalLayout_13.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.radioButton_18 = QtGui.QRadioButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_18.setFont(font)
        self.radioButton_18.setChecked(True)
        self.radioButton_18.setObjectName("radioButton_18")
        self.horizontalLayout_13.addWidget(self.radioButton_18)
        self.horizontalLayout_12.addWidget(self.groupBox_6)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_29 = QtGui.QLabel(self.sixthFrame)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_22.addWidget(self.label_29)
        self.lineEdit_21 = QtGui.QLineEdit(self.sixthFrame)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_22.addWidget(self.lineEdit_21)
        self.horizontalLayout_12.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_30 = QtGui.QLabel(self.sixthFrame)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_23.addWidget(self.label_30)
        self.lineEdit_22 = QtGui.QLineEdit(self.sixthFrame)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_23.addWidget(self.lineEdit_22)
        self.horizontalLayout_12.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_31 = QtGui.QLabel(self.sixthFrame)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_24.addWidget(self.label_31)
        self.lineEdit_23 = QtGui.QLineEdit(self.sixthFrame)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_24.addWidget(self.lineEdit_23)
        self.horizontalLayout_12.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_32 = QtGui.QLabel(self.sixthFrame)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_25.addWidget(self.label_32)
        self.lineEdit_24 = QtGui.QLineEdit(self.sixthFrame)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_25.addWidget(self.lineEdit_24)
        self.horizontalLayout_12.addLayout(self.verticalLayout_25)
        self.verticalLayout_26.addWidget(self.sixthFrame)
        self.label_35 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_26.addWidget(self.label_35)
        self.horizontalLayout_14.addWidget(self.frame)
        self.frame_9 = QtGui.QFrame(Frame)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.groupBox_7 = QtGui.QGroupBox(self.frame_9)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.jukesRadio = QtGui.QRadioButton(self.groupBox_7)
        self.jukesRadio.setChecked(True)
        self.jukesRadio.setObjectName("jukesRadio")
        self.verticalLayout_6.addWidget(self.jukesRadio)
        self.kimuraRadio = QtGui.QRadioButton(self.groupBox_7)
        self.kimuraRadio.setObjectName("kimuraRadio")
        self.verticalLayout_6.addWidget(self.kimuraRadio)
        self.haseRadio = QtGui.QRadioButton(self.groupBox_7)
        self.haseRadio.setObjectName("haseRadio")
        self.verticalLayout_6.addWidget(self.haseRadio)
        self.tamuraRadio = QtGui.QRadioButton(self.groupBox_7)
        self.tamuraRadio.setObjectName("tamuraRadio")
        self.verticalLayout_6.addWidget(self.tamuraRadio)
        self.verticalLayout_27.addWidget(self.groupBox_7)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.frame_9)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_25 = QtGui.QLineEdit(self.frame_9)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout.addWidget(self.lineEdit_25, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.frame_9)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.lineEdit_26 = QtGui.QLineEdit(self.frame_9)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout.addWidget(self.lineEdit_26, 1, 2, 1, 1)
        self.verticalLayout_27.addLayout(self.gridLayout)
        self.horizontalLayout_14.addWidget(self.frame_9)
        self.verticalLayout_28.addLayout(self.horizontalLayout_14)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setToolTip(QtGui.QApplication.translate("Frame", "Leave this screen without loosing any change", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("Frame", "EXIT", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setToolTip(QtGui.QApplication.translate("Frame", "Clear all data related to this historical model", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("Frame", "CLEAR", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("Frame", "Test and save data (Alt+o)", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Frame", "VALIDATE", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+V", None, QtGui.QApplication.UnicodeUTF8))
        self.setMutSeqLabel.setText(QtGui.QApplication.translate("Frame", "Set mutation Model (Sequences)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Frame", "Mean mutation\n"
"rate (per site\n"
"per generation)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_10.setText(QtGui.QApplication.translate("Frame", "Unif", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_11.setText(QtGui.QApplication.translate("Frame", "Log-u", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_12.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_13.setText(QtGui.QApplication.translate("Frame", "1.00E-8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_14.setText(QtGui.QApplication.translate("Frame", "1.00E-7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Frame", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Frame", "Individuals locus\n"
"mutation rate\n"
"(Gamma distribution\n"
"around mean)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_9.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_9.setText(QtGui.QApplication.translate("Frame", "1.00E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_10.setText(QtGui.QApplication.translate("Frame", "1.00E-6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_11.setText(QtGui.QApplication.translate("Frame", "Mean µ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Frame", "Shape (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_12.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Mean\n"
"coefficient\n"
"k_C/T", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Frame", "Unif", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Frame", "Log-u", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("Frame", "0.050", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("Frame", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "Individuals locus\n"
"coefficient k_C/T\n"
"(Gamma distribution\n"
"around mean)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_5.setText(QtGui.QApplication.translate("Frame", "0.050", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_6.setText(QtGui.QApplication.translate("Frame", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Frame", "Shape (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_8.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Frame", "Mean coefficient\n"
"k_A/G", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_13.setText(QtGui.QApplication.translate("Frame", "Unif", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_14.setText(QtGui.QApplication.translate("Frame", "Log-u", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_15.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_17.setText(QtGui.QApplication.translate("Frame", "0.050", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_18.setText(QtGui.QApplication.translate("Frame", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Frame", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Frame", "Individuals locus\n"
"coefficient k_A/G\n"
"(Gamma distribution\n"
"around mean)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_18.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_21.setText(QtGui.QApplication.translate("Frame", "0.050", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_22.setText(QtGui.QApplication.translate("Frame", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Frame", "Shape (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_24.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Frame", "(1) Set the shape to 0 if you want all individuals loci to take the same value (=mean)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Frame", "Mutation model", None, QtGui.QApplication.UnicodeUTF8))
        self.jukesRadio.setText(QtGui.QApplication.translate("Frame", "Jukes Kantor (1969)", None, QtGui.QApplication.UnicodeUTF8))
        self.kimuraRadio.setText(QtGui.QApplication.translate("Frame", "Kimura 2 Parameters (1980)", None, QtGui.QApplication.UnicodeUTF8))
        self.haseRadio.setText(QtGui.QApplication.translate("Frame", "Hasegawa-Kishino-Yano (1985)", None, QtGui.QApplication.UnicodeUTF8))
        self.tamuraRadio.setText(QtGui.QApplication.translate("Frame", "Tamura Nei (1993)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "% of invariant sites :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_25.setText(QtGui.QApplication.translate("Frame", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Shape of the gamma :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_26.setText(QtGui.QApplication.translate("Frame", "2.00", None, QtGui.QApplication.UnicodeUTF8))

