# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/setMutationmodel.ui'
#
# Created: Wed Jan 26 11:12:35 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(930, 673)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_6 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtGui.QFrame(Frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.exitButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_9.addWidget(self.exitButton)
        self.clearButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_9.addWidget(self.clearButton)
        self.okButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_9.addWidget(self.okButton)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.setMutMsLabel = QtGui.QLabel(Frame)
        self.setMutMsLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setMutMsLabel.setFont(font)
        self.setMutMsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.setMutMsLabel.setObjectName("setMutMsLabel")
        self.verticalLayout_6.addWidget(self.setMutMsLabel)
        self.frame = QtGui.QFrame(Frame)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_5 = QtGui.QFrame(self.frame)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtGui.QLabel(self.frame_5)
        self.label_18.setMinimumSize(QtCore.QSize(110, 0))
        self.label_18.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.groupBox_4 = QtGui.QGroupBox(self.frame_5)
        self.groupBox_4.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(240, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_10.setChecked(False)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_8.addWidget(self.radioButton_10)
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_11.setChecked(True)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_8.addWidget(self.radioButton_11)
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_8.addWidget(self.radioButton_12)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_19 = QtGui.QLabel(self.frame_5)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_14.addWidget(self.label_19)
        self.lineEdit_13 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_14.addWidget(self.lineEdit_13)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_20 = QtGui.QLabel(self.frame_5)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_15.addWidget(self.label_20)
        self.lineEdit_14 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_15.addWidget(self.lineEdit_14)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_21 = QtGui.QLabel(self.frame_5)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_16.addWidget(self.label_21)
        self.lineEdit_15 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_16.addWidget(self.lineEdit_15)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_22 = QtGui.QLabel(self.frame_5)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_17.addWidget(self.label_22)
        self.lineEdit_16 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_17.addWidget(self.lineEdit_16)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.verticalLayout_26.addWidget(self.frame_5)
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtGui.QLabel(self.frame_4)
        self.label_13.setMinimumSize(QtCore.QSize(110, 0))
        self.label_13.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.groupBox_3 = QtGui.QGroupBox(self.frame_4)
        self.groupBox_3.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(240, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_6.addWidget(self.radioButton_9)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_14 = QtGui.QLabel(self.frame_4)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.lineEdit_9 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_10.addWidget(self.lineEdit_9)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_15 = QtGui.QLabel(self.frame_4)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15)
        self.lineEdit_10 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_11.addWidget(self.lineEdit_10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtGui.QLabel(self.frame_4)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.lineEdit_11 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_12.addWidget(self.lineEdit_11)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_17 = QtGui.QLabel(self.frame_4)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        self.lineEdit_12 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_13.addWidget(self.lineEdit_12)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_26.addWidget(self.frame_4)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(110, 0))
        self.label_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(240, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit = QtGui.QLineEdit(self.frame_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lineEdit_3 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_26.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setMinimumSize(QtCore.QSize(110, 0))
        self.label_8.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_2.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(240, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_4.addWidget(self.radioButton_6)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.lineEdit_5 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_7.addWidget(self.lineEdit_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_8.addWidget(self.lineEdit_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtGui.QLabel(self.frame_3)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.lineEdit_8 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_9.addWidget(self.lineEdit_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_26.addWidget(self.frame_3)
        self.frame_7 = QtGui.QFrame(self.frame)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_23 = QtGui.QLabel(self.frame_7)
        self.label_23.setMinimumSize(QtCore.QSize(110, 0))
        self.label_23.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.groupBox_5 = QtGui.QGroupBox(self.frame_7)
        self.groupBox_5.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(240, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_11.addWidget(self.radioButton_13)
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_14.setChecked(True)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_11.addWidget(self.radioButton_14)
        self.radioButton_15 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_11.addWidget(self.radioButton_15)
        self.horizontalLayout_10.addWidget(self.groupBox_5)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_24 = QtGui.QLabel(self.frame_7)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_18.addWidget(self.label_24)
        self.lineEdit_17 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_18.addWidget(self.lineEdit_17)
        self.horizontalLayout_10.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_25 = QtGui.QLabel(self.frame_7)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_19.addWidget(self.label_25)
        self.lineEdit_18 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_19.addWidget(self.lineEdit_18)
        self.horizontalLayout_10.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_26 = QtGui.QLabel(self.frame_7)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_20.addWidget(self.label_26)
        self.lineEdit_19 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_20.addWidget(self.lineEdit_19)
        self.horizontalLayout_10.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_27 = QtGui.QLabel(self.frame_7)
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_21.addWidget(self.label_27)
        self.lineEdit_20 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_21.addWidget(self.lineEdit_20)
        self.horizontalLayout_10.addLayout(self.verticalLayout_21)
        self.verticalLayout_26.addWidget(self.frame_7)
        self.frame_8 = QtGui.QFrame(self.frame)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_12.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_28 = QtGui.QLabel(self.frame_8)
        self.label_28.setMinimumSize(QtCore.QSize(110, 0))
        self.label_28.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        self.groupBox_6 = QtGui.QGroupBox(self.frame_8)
        self.groupBox_6.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(240, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.radioButton_18 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_18.setChecked(True)
        self.radioButton_18.setObjectName("radioButton_18")
        self.horizontalLayout_13.addWidget(self.radioButton_18)
        self.horizontalLayout_12.addWidget(self.groupBox_6)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_29 = QtGui.QLabel(self.frame_8)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_22.addWidget(self.label_29)
        self.lineEdit_21 = QtGui.QLineEdit(self.frame_8)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_22.addWidget(self.lineEdit_21)
        self.horizontalLayout_12.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_30 = QtGui.QLabel(self.frame_8)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_23.addWidget(self.label_30)
        self.lineEdit_22 = QtGui.QLineEdit(self.frame_8)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_23.addWidget(self.lineEdit_22)
        self.horizontalLayout_12.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_31 = QtGui.QLabel(self.frame_8)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_24.addWidget(self.label_31)
        self.lineEdit_23 = QtGui.QLineEdit(self.frame_8)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_24.addWidget(self.lineEdit_23)
        self.horizontalLayout_12.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_32 = QtGui.QLabel(self.frame_8)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_25.addWidget(self.label_32)
        self.lineEdit_24 = QtGui.QLineEdit(self.frame_8)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_25.addWidget(self.lineEdit_24)
        self.horizontalLayout_12.addLayout(self.verticalLayout_25)
        self.verticalLayout_26.addWidget(self.frame_8)
        self.label_35 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_26.addWidget(self.label_35)
        self.label_34 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_26.addWidget(self.label_34)
        self.label_33 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_26.addWidget(self.label_33)
        self.verticalLayout_6.addWidget(self.frame)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setToolTip(QtGui.QApplication.translate("Frame", "Leave this screen without loosing any change", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("Frame", "EXIT", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setToolTip(QtGui.QApplication.translate("Frame", "Clear all data related to this historical model", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("Frame", "CLEAR", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("Frame", "Test and save data (Alt+o)", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Frame", "VALIDATE", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+V", None, QtGui.QApplication.UnicodeUTF8))
        self.setMutMsLabel.setText(QtGui.QApplication.translate("Frame", "Set mutation Model (Microsatellites)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Frame", "Mean\n"
"mutation\n"
"rate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_10.setText(QtGui.QApplication.translate("Frame", "Unif", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_11.setText(QtGui.QApplication.translate("Frame", "Log-u", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_12.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_13.setText(QtGui.QApplication.translate("Frame", "1.00E-005", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_14.setText(QtGui.QApplication.translate("Frame", "1.00E-3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Frame", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Frame", "Individuals locus\n"
"mutation rate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_9.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_9.setText(QtGui.QApplication.translate("Frame", "1.00E-005", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_10.setText(QtGui.QApplication.translate("Frame", "1.00E-002", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_11.setText(QtGui.QApplication.translate("Frame", "Mean µ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Frame", "Shape (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_12.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Mean\n"
"coefficient P", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Frame", "Unif", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Frame", "Log-u", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("Frame", "1.00E-001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Maximum (2)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("Frame", "6.00E-001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "Individuals locus\n"
"coefficient P", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_5.setText(QtGui.QApplication.translate("Frame", "1.00E-002", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_6.setText(QtGui.QApplication.translate("Frame", "9.00E-001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_7.setText(QtGui.QApplication.translate("Frame", "Mean P", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Frame", "Shape (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_8.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Frame", "Mean\n"
"SNI\n"
"rate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_13.setText(QtGui.QApplication.translate("Frame", "Unif", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_14.setText(QtGui.QApplication.translate("Frame", "Log-u", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_15.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_17.setText(QtGui.QApplication.translate("Frame", "1.00E-008", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Frame", "Maximum (3)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_18.setText(QtGui.QApplication.translate("Frame", "1.00E-004", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Frame", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Frame", "Individuals\n"
"locus SNI rate", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_18.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_21.setText(QtGui.QApplication.translate("Frame", "1.00E-009", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_22.setText(QtGui.QApplication.translate("Frame", "1.00E-003", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_23.setText(QtGui.QApplication.translate("Frame", "Mean µ_SNI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Frame", "Shape (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_24.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Frame", "(1) Set the shape to 0 if you want all individuals loci to take the same value (=mean)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Frame", "(2) Set the maximum to 0 if you only want a Stepwise Mutation Model (SMM)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Frame", "(3) Set the maximum to 0 if you want to exclude Singlz Nucleotide Insertion/deletions", None, QtGui.QApplication.UnicodeUTF8))

