# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/setSummaryStatistics.ui'
#
# Created: Tue Jan 25 10:04:03 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(891, 769)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtGui.QFrame(Frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.exitButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_9.addWidget(self.exitButton)
        self.clearButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_9.addWidget(self.clearButton)
        self.okButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_9.addWidget(self.okButton)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.sumStatLabel = QtGui.QLabel(Frame)
        self.sumStatLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sumStatLabel.setFont(font)
        self.sumStatLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sumStatLabel.setObjectName("sumStatLabel")
        self.verticalLayout_3.addWidget(self.sumStatLabel)
        self.oneScroll = QtGui.QScrollArea(Frame)
        self.oneScroll.setWidgetResizable(True)
        self.oneScroll.setObjectName("oneScroll")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.oneScroll)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 869, 194))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_24 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setMinimumSize(QtCore.QSize(0, 15))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_9.addWidget(self.label_24)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_8 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_8.setMinimumSize(QtCore.QSize(275, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(275, 16777215))
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_18 = QtGui.QLabel(self.frame_8)
        self.label_18.setMinimumSize(QtCore.QSize(0, 14))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtGui.QLabel(self.frame_8)
        self.label_19.setMinimumSize(QtCore.QSize(0, 14))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.allMnoaButton = QtGui.QPushButton(self.frame_8)
        self.allMnoaButton.setMinimumSize(QtCore.QSize(25, 14))
        self.allMnoaButton.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allMnoaButton.setFont(font)
        self.allMnoaButton.setObjectName("allMnoaButton")
        self.horizontalLayout_18.addWidget(self.allMnoaButton)
        self.noneMnoaButton = QtGui.QPushButton(self.frame_8)
        self.noneMnoaButton.setMinimumSize(QtCore.QSize(35, 14))
        self.noneMnoaButton.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneMnoaButton.setFont(font)
        self.noneMnoaButton.setObjectName("noneMnoaButton")
        self.horizontalLayout_18.addWidget(self.noneMnoaButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtGui.QLabel(self.frame_8)
        self.label_20.setMinimumSize(QtCore.QSize(0, 14))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.allMgdButton = QtGui.QPushButton(self.frame_8)
        self.allMgdButton.setMinimumSize(QtCore.QSize(25, 14))
        self.allMgdButton.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allMgdButton.setFont(font)
        self.allMgdButton.setObjectName("allMgdButton")
        self.horizontalLayout_21.addWidget(self.allMgdButton)
        self.noneMgdButton = QtGui.QPushButton(self.frame_8)
        self.noneMgdButton.setMinimumSize(QtCore.QSize(35, 14))
        self.noneMgdButton.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneMgdButton.setFont(font)
        self.noneMgdButton.setObjectName("noneMgdButton")
        self.horizontalLayout_21.addWidget(self.noneMgdButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_21 = QtGui.QLabel(self.frame_8)
        self.label_21.setMinimumSize(QtCore.QSize(0, 14))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_20.addWidget(self.label_21)
        self.allMsvButton = QtGui.QPushButton(self.frame_8)
        self.allMsvButton.setMinimumSize(QtCore.QSize(25, 14))
        self.allMsvButton.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allMsvButton.setFont(font)
        self.allMsvButton.setObjectName("allMsvButton")
        self.horizontalLayout_20.addWidget(self.allMsvButton)
        self.noneMsvButton = QtGui.QPushButton(self.frame_8)
        self.noneMsvButton.setMinimumSize(QtCore.QSize(35, 14))
        self.noneMsvButton.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneMsvButton.setFont(font)
        self.noneMsvButton.setObjectName("noneMsvButton")
        self.horizontalLayout_20.addWidget(self.noneMsvButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_22 = QtGui.QLabel(self.frame_8)
        self.label_22.setMinimumSize(QtCore.QSize(0, 14))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.allMgwButton = QtGui.QPushButton(self.frame_8)
        self.allMgwButton.setMinimumSize(QtCore.QSize(25, 14))
        self.allMgwButton.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allMgwButton.setFont(font)
        self.allMgwButton.setObjectName("allMgwButton")
        self.horizontalLayout_19.addWidget(self.allMgwButton)
        self.noneMgwButton = QtGui.QPushButton(self.frame_8)
        self.noneMgwButton.setMinimumSize(QtCore.QSize(35, 14))
        self.noneMgwButton.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneMgwButton.setFont(font)
        self.noneMgwButton.setObjectName("noneMgwButton")
        self.horizontalLayout_19.addWidget(self.noneMgwButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_9.setMinimumSize(QtCore.QSize(85, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(85, 16777215))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.oneSampleLabel = QtGui.QLabel(self.frame_9)
        self.oneSampleLabel.setMinimumSize(QtCore.QSize(0, 14))
        self.oneSampleLabel.setMaximumSize(QtCore.QSize(5000, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.oneSampleLabel.setFont(font)
        self.oneSampleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.oneSampleLabel.setObjectName("oneSampleLabel")
        self.verticalLayout_4.addWidget(self.oneSampleLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.mnoaCheck = QtGui.QCheckBox(self.frame_9)
        self.mnoaCheck.setMinimumSize(QtCore.QSize(20, 14))
        self.mnoaCheck.setMaximumSize(QtCore.QSize(20, 14))
        self.mnoaCheck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mnoaCheck.setObjectName("mnoaCheck")
        self.horizontalLayout_3.addWidget(self.mnoaCheck)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.mgdCheck = QtGui.QCheckBox(self.frame_9)
        self.mgdCheck.setMinimumSize(QtCore.QSize(20, 14))
        self.mgdCheck.setMaximumSize(QtCore.QSize(20, 14))
        self.mgdCheck.setObjectName("mgdCheck")
        self.horizontalLayout_7.addWidget(self.mgdCheck)
        spacerItem3 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.msvCheck = QtGui.QCheckBox(self.frame_9)
        self.msvCheck.setMinimumSize(QtCore.QSize(20, 14))
        self.msvCheck.setMaximumSize(QtCore.QSize(20, 14))
        self.msvCheck.setObjectName("msvCheck")
        self.horizontalLayout_8.addWidget(self.msvCheck)
        spacerItem5 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.mgwCheck = QtGui.QCheckBox(self.frame_9)
        self.mgwCheck.setMinimumSize(QtCore.QSize(20, 14))
        self.mgwCheck.setMaximumSize(QtCore.QSize(20, 14))
        self.mgwCheck.setObjectName("mgwCheck")
        self.horizontalLayout_10.addWidget(self.mgwCheck)
        spacerItem7 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.oneScroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.oneScroll)
        self.twoScroll = QtGui.QScrollArea(Frame)
        self.twoScroll.setWidgetResizable(True)
        self.twoScroll.setObjectName("twoScroll")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.twoScroll)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 869, 255))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_25 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_25.setMinimumSize(QtCore.QSize(0, 15))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_25.setObjectName("label_25")
        self.verticalLayout_12.addWidget(self.label_25)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_10 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_10.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_26 = QtGui.QLabel(self.frame_10)
        self.label_26.setMinimumSize(QtCore.QSize(0, 14))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_26.setObjectName("label_26")
        self.verticalLayout_8.addWidget(self.label_26)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_27 = QtGui.QLabel(self.frame_10)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_22.addWidget(self.label_27)
        self.allMnoa2Button = QtGui.QPushButton(self.frame_10)
        self.allMnoa2Button.setMinimumSize(QtCore.QSize(25, 14))
        self.allMnoa2Button.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allMnoa2Button.setFont(font)
        self.allMnoa2Button.setObjectName("allMnoa2Button")
        self.horizontalLayout_22.addWidget(self.allMnoa2Button)
        self.noneMnoa2Button = QtGui.QPushButton(self.frame_10)
        self.noneMnoa2Button.setMinimumSize(QtCore.QSize(35, 14))
        self.noneMnoa2Button.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneMnoa2Button.setFont(font)
        self.noneMnoa2Button.setObjectName("noneMnoa2Button")
        self.horizontalLayout_22.addWidget(self.noneMnoa2Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtGui.QLabel(self.frame_10)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        self.allMgd2Button = QtGui.QPushButton(self.frame_10)
        self.allMgd2Button.setMinimumSize(QtCore.QSize(25, 14))
        self.allMgd2Button.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allMgd2Button.setFont(font)
        self.allMgd2Button.setObjectName("allMgd2Button")
        self.horizontalLayout_23.addWidget(self.allMgd2Button)
        self.noneMgd2Button = QtGui.QPushButton(self.frame_10)
        self.noneMgd2Button.setMinimumSize(QtCore.QSize(35, 14))
        self.noneMgd2Button.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneMgd2Button.setFont(font)
        self.noneMgd2Button.setObjectName("noneMgd2Button")
        self.horizontalLayout_23.addWidget(self.noneMgd2Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_29 = QtGui.QLabel(self.frame_10)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_24.addWidget(self.label_29)
        self.allMsv2Button = QtGui.QPushButton(self.frame_10)
        self.allMsv2Button.setMinimumSize(QtCore.QSize(25, 14))
        self.allMsv2Button.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allMsv2Button.setFont(font)
        self.allMsv2Button.setObjectName("allMsv2Button")
        self.horizontalLayout_24.addWidget(self.allMsv2Button)
        self.noneMsv2Button = QtGui.QPushButton(self.frame_10)
        self.noneMsv2Button.setMinimumSize(QtCore.QSize(35, 14))
        self.noneMsv2Button.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneMsv2Button.setFont(font)
        self.noneMsv2Button.setObjectName("noneMsv2Button")
        self.horizontalLayout_24.addWidget(self.noneMsv2Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_30 = QtGui.QLabel(self.frame_10)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_25.addWidget(self.label_30)
        self.allFst2Button = QtGui.QPushButton(self.frame_10)
        self.allFst2Button.setMinimumSize(QtCore.QSize(25, 14))
        self.allFst2Button.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allFst2Button.setFont(font)
        self.allFst2Button.setObjectName("allFst2Button")
        self.horizontalLayout_25.addWidget(self.allFst2Button)
        self.noneFst2Button = QtGui.QPushButton(self.frame_10)
        self.noneFst2Button.setMinimumSize(QtCore.QSize(35, 14))
        self.noneFst2Button.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneFst2Button.setFont(font)
        self.noneFst2Button.setObjectName("noneFst2Button")
        self.horizontalLayout_25.addWidget(self.noneFst2Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_31 = QtGui.QLabel(self.frame_10)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_26.addWidget(self.label_31)
        self.allCi2Button = QtGui.QPushButton(self.frame_10)
        self.allCi2Button.setMinimumSize(QtCore.QSize(25, 14))
        self.allCi2Button.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allCi2Button.setFont(font)
        self.allCi2Button.setObjectName("allCi2Button")
        self.horizontalLayout_26.addWidget(self.allCi2Button)
        self.noneCi2Button = QtGui.QPushButton(self.frame_10)
        self.noneCi2Button.setMinimumSize(QtCore.QSize(35, 14))
        self.noneCi2Button.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneCi2Button.setFont(font)
        self.noneCi2Button.setObjectName("noneCi2Button")
        self.horizontalLayout_26.addWidget(self.noneCi2Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_32 = QtGui.QLabel(self.frame_10)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_27.addWidget(self.label_32)
        self.allSad2Button = QtGui.QPushButton(self.frame_10)
        self.allSad2Button.setMinimumSize(QtCore.QSize(25, 14))
        self.allSad2Button.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allSad2Button.setFont(font)
        self.allSad2Button.setObjectName("allSad2Button")
        self.horizontalLayout_27.addWidget(self.allSad2Button)
        self.noneSad2Button = QtGui.QPushButton(self.frame_10)
        self.noneSad2Button.setMinimumSize(QtCore.QSize(35, 14))
        self.noneSad2Button.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneSad2Button.setFont(font)
        self.noneSad2Button.setObjectName("noneSad2Button")
        self.horizontalLayout_27.addWidget(self.noneSad2Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_34 = QtGui.QLabel(self.frame_10)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_28.addWidget(self.label_34)
        self.allDd2Button = QtGui.QPushButton(self.frame_10)
        self.allDd2Button.setMinimumSize(QtCore.QSize(25, 14))
        self.allDd2Button.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allDd2Button.setFont(font)
        self.allDd2Button.setObjectName("allDd2Button")
        self.horizontalLayout_28.addWidget(self.allDd2Button)
        self.noneDd2Button = QtGui.QPushButton(self.frame_10)
        self.noneDd2Button.setMinimumSize(QtCore.QSize(35, 14))
        self.noneDd2Button.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneDd2Button.setFont(font)
        self.noneDd2Button.setObjectName("noneDd2Button")
        self.horizontalLayout_28.addWidget(self.noneDd2Button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_11.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setMargin(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.twoSampleLabel = QtGui.QLabel(self.frame_11)
        self.twoSampleLabel.setMinimumSize(QtCore.QSize(0, 14))
        self.twoSampleLabel.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.twoSampleLabel.setFont(font)
        self.twoSampleLabel.setObjectName("twoSampleLabel")
        self.verticalLayout_5.addWidget(self.twoSampleLabel)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem8 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.mnoa2Check = QtGui.QCheckBox(self.frame_11)
        self.mnoa2Check.setMinimumSize(QtCore.QSize(20, 14))
        self.mnoa2Check.setMaximumSize(QtCore.QSize(20, 14))
        self.mnoa2Check.setObjectName("mnoa2Check")
        self.horizontalLayout_16.addWidget(self.mnoa2Check)
        spacerItem9 = QtGui.QSpacerItem(17, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem10 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.mgd2Check = QtGui.QCheckBox(self.frame_11)
        self.mgd2Check.setMinimumSize(QtCore.QSize(20, 14))
        self.mgd2Check.setMaximumSize(QtCore.QSize(20, 14))
        self.mgd2Check.setObjectName("mgd2Check")
        self.horizontalLayout_15.addWidget(self.mgd2Check)
        spacerItem11 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem12 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.msv2Check = QtGui.QCheckBox(self.frame_11)
        self.msv2Check.setMinimumSize(QtCore.QSize(20, 14))
        self.msv2Check.setMaximumSize(QtCore.QSize(20, 14))
        self.msv2Check.setObjectName("msv2Check")
        self.horizontalLayout_14.addWidget(self.msv2Check)
        spacerItem13 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem14 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.fst2Check = QtGui.QCheckBox(self.frame_11)
        self.fst2Check.setMinimumSize(QtCore.QSize(20, 14))
        self.fst2Check.setMaximumSize(QtCore.QSize(20, 14))
        self.fst2Check.setObjectName("fst2Check")
        self.horizontalLayout_13.addWidget(self.fst2Check)
        spacerItem15 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ci2LeftCheck = QtGui.QCheckBox(self.frame_11)
        self.ci2LeftCheck.setMinimumSize(QtCore.QSize(20, 14))
        self.ci2LeftCheck.setMaximumSize(QtCore.QSize(20, 14))
        self.ci2LeftCheck.setObjectName("ci2LeftCheck")
        self.horizontalLayout_6.addWidget(self.ci2LeftCheck)
        self.ci2RightCheck = QtGui.QCheckBox(self.frame_11)
        self.ci2RightCheck.setMinimumSize(QtCore.QSize(20, 14))
        self.ci2RightCheck.setMaximumSize(QtCore.QSize(20, 14))
        self.ci2RightCheck.setObjectName("ci2RightCheck")
        self.horizontalLayout_6.addWidget(self.ci2RightCheck)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem16 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem16)
        self.sad2Check = QtGui.QCheckBox(self.frame_11)
        self.sad2Check.setMinimumSize(QtCore.QSize(20, 14))
        self.sad2Check.setMaximumSize(QtCore.QSize(20, 14))
        self.sad2Check.setObjectName("sad2Check")
        self.horizontalLayout_12.addWidget(self.sad2Check)
        spacerItem17 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem18 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.dd2Check = QtGui.QCheckBox(self.frame_11)
        self.dd2Check.setMinimumSize(QtCore.QSize(20, 14))
        self.dd2Check.setMaximumSize(QtCore.QSize(20, 14))
        self.dd2Check.setObjectName("dd2Check")
        self.horizontalLayout_11.addWidget(self.dd2Check)
        spacerItem19 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5.addWidget(self.frame_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.twoScroll.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.twoScroll)
        self.admixScroll = QtGui.QScrollArea(Frame)
        self.admixScroll.setWidgetResizable(True)
        self.admixScroll.setObjectName("admixScroll")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget(self.admixScroll)
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 869, 194))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.frame.setMinimumSize(QtCore.QSize(230, 0))
        self.frame.setMaximumSize(QtCore.QSize(230, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addAdmixButton = QtGui.QPushButton(self.frame)
        self.addAdmixButton.setObjectName("addAdmixButton")
        self.verticalLayout.addWidget(self.addAdmixButton)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.adm1Combo = QtGui.QComboBox(self.frame)
        self.adm1Combo.setObjectName("adm1Combo")
        self.horizontalLayout.addWidget(self.adm1Combo)
        self.adm2Combo = QtGui.QComboBox(self.frame)
        self.adm2Combo.setObjectName("adm2Combo")
        self.horizontalLayout.addWidget(self.adm2Combo)
        self.adm3Combo = QtGui.QComboBox(self.frame)
        self.adm3Combo.setObjectName("adm3Combo")
        self.horizontalLayout.addWidget(self.adm3Combo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_29.addWidget(self.label_2)
        self.allMl3Button = QtGui.QPushButton(self.frame)
        self.allMl3Button.setMinimumSize(QtCore.QSize(25, 14))
        self.allMl3Button.setMaximumSize(QtCore.QSize(25, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.allMl3Button.setFont(font)
        self.allMl3Button.setObjectName("allMl3Button")
        self.horizontalLayout_29.addWidget(self.allMl3Button)
        self.noneMl3Button = QtGui.QPushButton(self.frame)
        self.noneMl3Button.setMinimumSize(QtCore.QSize(35, 14))
        self.noneMl3Button.setMaximumSize(QtCore.QSize(35, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.noneMl3Button.setFont(font)
        self.noneMl3Button.setObjectName("noneMl3Button")
        self.horizontalLayout_29.addWidget(self.noneMl3Button)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_12 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_12.setMinimumSize(QtCore.QSize(120, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.threeSampleLabel = QtGui.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.threeSampleLabel.setFont(font)
        self.threeSampleLabel.setObjectName("threeSampleLabel")
        self.verticalLayout_6.addWidget(self.threeSampleLabel)
        self.rmButton = QtGui.QPushButton(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rmButton.setFont(font)
        self.rmButton.setObjectName("rmButton")
        self.verticalLayout_6.addWidget(self.rmButton)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem20 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem20)
        self.ml3Check = QtGui.QCheckBox(self.frame_12)
        self.ml3Check.setMinimumSize(QtCore.QSize(20, 0))
        self.ml3Check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ml3Check.setObjectName("ml3Check")
        self.horizontalLayout_17.addWidget(self.ml3Check)
        spacerItem21 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem21)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.admixScroll.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.admixScroll)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setToolTip(QtGui.QApplication.translate("Frame", "Leave this screen without loosing any change", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("Frame", "EXIT", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setToolTip(QtGui.QApplication.translate("Frame", "Clear all data related to this historical model", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("Frame", "CLEAR", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("Frame", "Test and save data (Alt+o)", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Frame", "VALIDATE", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+V", None, QtGui.QApplication.UnicodeUTF8))
        self.sumStatLabel.setText(QtGui.QApplication.translate("Frame", "Summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Frame", "One Sample summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Frame", "Mean number of alleles", None, QtGui.QApplication.UnicodeUTF8))
        self.allMnoaButton.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneMnoaButton.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Frame", "Mean genic diversity", None, QtGui.QApplication.UnicodeUTF8))
        self.allMgdButton.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneMgdButton.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Frame", "Mean size variance", None, QtGui.QApplication.UnicodeUTF8))
        self.allMsvButton.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneMsvButton.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Frame", "Mean Garza-Williamson\'s M", None, QtGui.QApplication.UnicodeUTF8))
        self.allMgwButton.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneMgwButton.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.oneSampleLabel.setText(QtGui.QApplication.translate("Frame", "Samp 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Frame", "Two Sample summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Frame", "Mean number of alleles", None, QtGui.QApplication.UnicodeUTF8))
        self.allMnoa2Button.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneMnoa2Button.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Frame", "Mean genic diversity", None, QtGui.QApplication.UnicodeUTF8))
        self.allMgd2Button.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneMgd2Button.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Frame", "Mean size variance", None, QtGui.QApplication.UnicodeUTF8))
        self.allMsv2Button.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneMsv2Button.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Frame", "Fst", None, QtGui.QApplication.UnicodeUTF8))
        self.allFst2Button.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneFst2Button.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Frame", "Classification index", None, QtGui.QApplication.UnicodeUTF8))
        self.allCi2Button.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneCi2Button.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Frame", "Shared allele distance", None, QtGui.QApplication.UnicodeUTF8))
        self.allSad2Button.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneSad2Button.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Frame", "(dµ)² distance", None, QtGui.QApplication.UnicodeUTF8))
        self.allDd2Button.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneDd2Button.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.twoSampleLabel.setText(QtGui.QApplication.translate("Frame", "Samp 1&2", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Admixture summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.addAdmixButton.setText(QtGui.QApplication.translate("Frame", "add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Maximum likelihood\n"
"(Choisy et al, 2004)", None, QtGui.QApplication.UnicodeUTF8))
        self.allMl3Button.setText(QtGui.QApplication.translate("Frame", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.noneMl3Button.setText(QtGui.QApplication.translate("Frame", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.threeSampleLabel.setText(QtGui.QApplication.translate("Frame", "Samp 1&2&3", None, QtGui.QApplication.UnicodeUTF8))
        self.rmButton.setText(QtGui.QApplication.translate("Frame", "remove", None, QtGui.QApplication.UnicodeUTF8))

