# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/setSummaryStatistics.ui'
#
# Created: Mon Jan 24 17:19:20 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(895, 704)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtGui.QFrame(Frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.exitButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_9.addWidget(self.exitButton)
        self.clearButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_9.addWidget(self.clearButton)
        self.okButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_9.addWidget(self.okButton)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.sumStatLabel = QtGui.QLabel(Frame)
        self.sumStatLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sumStatLabel.setFont(font)
        self.sumStatLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sumStatLabel.setObjectName("sumStatLabel")
        self.verticalLayout_3.addWidget(self.sumStatLabel)
        self.scrollArea = QtGui.QScrollArea(Frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 873, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_24 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setMinimumSize(QtCore.QSize(0, 15))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_9.addWidget(self.label_24)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_8 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_8.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_18 = QtGui.QLabel(self.frame_8)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.frame_8)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.label_20 = QtGui.QLabel(self.frame_8)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.frame_8)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.frame_8)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_9.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.oneSampleLabel = QtGui.QLabel(self.frame_9)
        self.oneSampleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.oneSampleLabel.setObjectName("oneSampleLabel")
        self.verticalLayout_4.addWidget(self.oneSampleLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.mnoaCheck = QtGui.QCheckBox(self.frame_9)
        self.mnoaCheck.setMinimumSize(QtCore.QSize(20, 0))
        self.mnoaCheck.setMaximumSize(QtCore.QSize(20, 16777215))
        self.mnoaCheck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mnoaCheck.setObjectName("mnoaCheck")
        self.horizontalLayout_3.addWidget(self.mnoaCheck)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.mgdCheck = QtGui.QCheckBox(self.frame_9)
        self.mgdCheck.setMinimumSize(QtCore.QSize(20, 0))
        self.mgdCheck.setMaximumSize(QtCore.QSize(20, 16777215))
        self.mgdCheck.setObjectName("mgdCheck")
        self.horizontalLayout_7.addWidget(self.mgdCheck)
        spacerItem3 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.msvCheck = QtGui.QCheckBox(self.frame_9)
        self.msvCheck.setMinimumSize(QtCore.QSize(20, 0))
        self.msvCheck.setMaximumSize(QtCore.QSize(20, 16777215))
        self.msvCheck.setObjectName("msvCheck")
        self.horizontalLayout_8.addWidget(self.msvCheck)
        spacerItem5 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.mgwCheck = QtGui.QCheckBox(self.frame_9)
        self.mgwCheck.setMinimumSize(QtCore.QSize(20, 0))
        self.mgwCheck.setMaximumSize(QtCore.QSize(20, 16777215))
        self.mgwCheck.setObjectName("mgwCheck")
        self.horizontalLayout_10.addWidget(self.mgwCheck)
        spacerItem7 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.scrollArea_2 = QtGui.QScrollArea(Frame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 873, 260))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_25 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_25.setMinimumSize(QtCore.QSize(0, 15))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_25.setObjectName("label_25")
        self.verticalLayout_12.addWidget(self.label_25)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_10 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_10.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_26 = QtGui.QLabel(self.frame_10)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_10.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(self.frame_10)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.label_28 = QtGui.QLabel(self.frame_10)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_10.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.frame_10)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_10.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(self.frame_10)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_10.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.frame_10)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_10.addWidget(self.label_31)
        self.label_32 = QtGui.QLabel(self.frame_10)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_10.addWidget(self.label_32)
        self.label_34 = QtGui.QLabel(self.frame_10)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_10.addWidget(self.label_34)
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_11.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.twoSampleLabel = QtGui.QLabel(self.frame_11)
        self.twoSampleLabel.setObjectName("twoSampleLabel")
        self.verticalLayout_5.addWidget(self.twoSampleLabel)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem8 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.mnoa2Check = QtGui.QCheckBox(self.frame_11)
        self.mnoa2Check.setMinimumSize(QtCore.QSize(20, 0))
        self.mnoa2Check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.mnoa2Check.setObjectName("mnoa2Check")
        self.horizontalLayout_16.addWidget(self.mnoa2Check)
        spacerItem9 = QtGui.QSpacerItem(17, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem10 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.mgd2Check = QtGui.QCheckBox(self.frame_11)
        self.mgd2Check.setMinimumSize(QtCore.QSize(20, 0))
        self.mgd2Check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.mgd2Check.setObjectName("mgd2Check")
        self.horizontalLayout_15.addWidget(self.mgd2Check)
        spacerItem11 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem12 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.msv2Check = QtGui.QCheckBox(self.frame_11)
        self.msv2Check.setMinimumSize(QtCore.QSize(20, 0))
        self.msv2Check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.msv2Check.setObjectName("msv2Check")
        self.horizontalLayout_14.addWidget(self.msv2Check)
        spacerItem13 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem14 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.fst2Check = QtGui.QCheckBox(self.frame_11)
        self.fst2Check.setMinimumSize(QtCore.QSize(20, 0))
        self.fst2Check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.fst2Check.setObjectName("fst2Check")
        self.horizontalLayout_13.addWidget(self.fst2Check)
        spacerItem15 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ci2LeftCheck = QtGui.QCheckBox(self.frame_11)
        self.ci2LeftCheck.setMinimumSize(QtCore.QSize(20, 0))
        self.ci2LeftCheck.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ci2LeftCheck.setObjectName("ci2LeftCheck")
        self.horizontalLayout_6.addWidget(self.ci2LeftCheck)
        self.ci2RightCheck = QtGui.QCheckBox(self.frame_11)
        self.ci2RightCheck.setMinimumSize(QtCore.QSize(20, 0))
        self.ci2RightCheck.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ci2RightCheck.setObjectName("ci2RightCheck")
        self.horizontalLayout_6.addWidget(self.ci2RightCheck)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem16 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem16)
        self.sad2Check = QtGui.QCheckBox(self.frame_11)
        self.sad2Check.setMinimumSize(QtCore.QSize(20, 0))
        self.sad2Check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.sad2Check.setObjectName("sad2Check")
        self.horizontalLayout_12.addWidget(self.sad2Check)
        spacerItem17 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem18 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.dd2Check = QtGui.QCheckBox(self.frame_11)
        self.dd2Check.setMinimumSize(QtCore.QSize(20, 0))
        self.dd2Check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.dd2Check.setObjectName("dd2Check")
        self.horizontalLayout_11.addWidget(self.dd2Check)
        spacerItem19 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5.addWidget(self.frame_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.scrollArea_3 = QtGui.QScrollArea(Frame)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget(self.scrollArea_3)
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 873, 139))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtGui.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtGui.QComboBox(self.frame)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.comboBox_3 = QtGui.QComboBox(self.frame)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout.addWidget(self.comboBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_12 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_12.setMinimumSize(QtCore.QSize(120, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.threeSampleLabel = QtGui.QLabel(self.frame_12)
        self.threeSampleLabel.setObjectName("threeSampleLabel")
        self.verticalLayout_6.addWidget(self.threeSampleLabel)
        self.rmButton = QtGui.QPushButton(self.frame_12)
        self.rmButton.setObjectName("rmButton")
        self.verticalLayout_6.addWidget(self.rmButton)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem20 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem20)
        self.ml3Check = QtGui.QCheckBox(self.frame_12)
        self.ml3Check.setMinimumSize(QtCore.QSize(20, 0))
        self.ml3Check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ml3Check.setObjectName("ml3Check")
        self.horizontalLayout_17.addWidget(self.ml3Check)
        spacerItem21 = QtGui.QSpacerItem(18, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem21)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.scrollArea_3)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setToolTip(QtGui.QApplication.translate("Frame", "Leave this screen without loosing any change", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("Frame", "EXIT", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setToolTip(QtGui.QApplication.translate("Frame", "Clear all data related to this historical model", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("Frame", "CLEAR", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("Frame", "Test and save data (Alt+o)", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Frame", "VALIDATE", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+V", None, QtGui.QApplication.UnicodeUTF8))
        self.sumStatLabel.setText(QtGui.QApplication.translate("Frame", "Summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Frame", "One Sample summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Frame", "Mean number of alleles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Frame", "Mean genic diversity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Frame", "Mean size variance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Frame", "Mean Garza-Williamson\'s M", None, QtGui.QApplication.UnicodeUTF8))
        self.oneSampleLabel.setText(QtGui.QApplication.translate("Frame", "Samp 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Frame", "One Sample summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Frame", "Mean number of alleles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Frame", "Mean genic diversity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Frame", "Mean size variance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Frame", "Fst", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Frame", "Classification index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Frame", "Shared allele distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Frame", "(dµ)² distance", None, QtGui.QApplication.UnicodeUTF8))
        self.twoSampleLabel.setText(QtGui.QApplication.translate("Frame", "Samp 1&2", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Admixture summary statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Frame", "add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Maximum likelihood (Choisy et al, 2004)", None, QtGui.QApplication.UnicodeUTF8))
        self.threeSampleLabel.setText(QtGui.QApplication.translate("Frame", "Samp 1&2&3", None, QtGui.QApplication.UnicodeUTF8))
        self.rmButton.setText(QtGui.QApplication.translate("Frame", "remove", None, QtGui.QApplication.UnicodeUTF8))

