# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/defineAnalysis.ui'
#
# Created: Mon Apr  4 11:54:27 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(1142, 704)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_6 = QtGui.QFrame(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.exitButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.horizontalLayout_9.addWidget(self.exitButton)
        self.okButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okButton.setFont(font)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout_9.addWidget(self.okButton)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.label = QtGui.QLabel(Frame)
        self.label.setMinimumSize(QtCore.QSize(0, 100))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(Frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 80))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.groupBox = QtGui.QGroupBox(Frame)
        self.groupBox.setMinimumSize(QtCore.QSize(600, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(600, 300))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.preEvRadio = QtGui.QRadioButton(self.groupBox)
        self.preEvRadio.setChecked(True)
        self.preEvRadio.setObjectName(_fromUtf8("preEvRadio"))
        self.horizontalLayout.addWidget(self.preEvRadio)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pcaCheck = QtGui.QCheckBox(self.groupBox)
        self.pcaCheck.setObjectName(_fromUtf8("pcaCheck"))
        self.verticalLayout.addWidget(self.pcaCheck)
        self.lossCheck = QtGui.QCheckBox(self.groupBox)
        self.lossCheck.setChecked(True)
        self.lossCheck.setObjectName(_fromUtf8("lossCheck"))
        self.verticalLayout.addWidget(self.lossCheck)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.estimateRadio = QtGui.QRadioButton(self.groupBox)
        self.estimateRadio.setMinimumSize(QtCore.QSize(0, 30))
        self.estimateRadio.setMaximumSize(QtCore.QSize(16777215, 30))
        self.estimateRadio.setObjectName(_fromUtf8("estimateRadio"))
        self.verticalLayout_4.addWidget(self.estimateRadio)
        self.biasRadio = QtGui.QRadioButton(self.groupBox)
        self.biasRadio.setMinimumSize(QtCore.QSize(0, 35))
        self.biasRadio.setMaximumSize(QtCore.QSize(16777215, 35))
        self.biasRadio.setObjectName(_fromUtf8("biasRadio"))
        self.verticalLayout_4.addWidget(self.biasRadio)
        self.comparisonRadio = QtGui.QRadioButton(self.groupBox)
        self.comparisonRadio.setMinimumSize(QtCore.QSize(0, 35))
        self.comparisonRadio.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comparisonRadio.setObjectName(_fromUtf8("comparisonRadio"))
        self.verticalLayout_4.addWidget(self.comparisonRadio)
        self.evaluateRadio = QtGui.QRadioButton(self.groupBox)
        self.evaluateRadio.setMinimumSize(QtCore.QSize(0, 35))
        self.evaluateRadio.setMaximumSize(QtCore.QSize(16777215, 35))
        self.evaluateRadio.setObjectName(_fromUtf8("evaluateRadio"))
        self.verticalLayout_4.addWidget(self.evaluateRadio)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.modCheckRadio = QtGui.QRadioButton(self.groupBox)
        self.modCheckRadio.setChecked(False)
        self.modCheckRadio.setObjectName(_fromUtf8("modCheckRadio"))
        self.horizontalLayout_4.addWidget(self.modCheckRadio)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.modCheckPcaCheck = QtGui.QCheckBox(self.groupBox)
        self.modCheckPcaCheck.setObjectName(_fromUtf8("modCheckPcaCheck"))
        self.verticalLayout_3.addWidget(self.modCheckPcaCheck)
        self.modCheckLossCheck = QtGui.QCheckBox(self.groupBox)
        self.modCheckLossCheck.setChecked(True)
        self.modCheckLossCheck.setObjectName(_fromUtf8("modCheckLossCheck"))
        self.verticalLayout_3.addWidget(self.modCheckLossCheck)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(Frame)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.analysisNameEdit = QtGui.QLineEdit(Frame)
        self.analysisNameEdit.setObjectName(_fromUtf8("analysisNameEdit"))
        self.horizontalLayout_3.addWidget(self.analysisNameEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setToolTip(QtGui.QApplication.translate("Frame", "Leave this screen without loosing any change", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("Frame", "CANCEL", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("Frame", "Test and save data (Alt+o)", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Frame", "VALIDATE", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+V", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "CHOOSE AN ANALYSIS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "The reference table...\n"
"Each record includes 2 parameters\n"
"The reference table has been built", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "Do you want to", None, QtGui.QApplication.UnicodeUTF8))
        self.preEvRadio.setText(QtGui.QApplication.translate("Frame", "Pre-evaluate scenario-prior combinations", None, QtGui.QApplication.UnicodeUTF8))
        self.pcaCheck.setText(QtGui.QApplication.translate("Frame", "Principal Component Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.lossCheck.setText(QtGui.QApplication.translate("Frame", "Locate observed S.S among simulated S.S.", None, QtGui.QApplication.UnicodeUTF8))
        self.estimateRadio.setText(QtGui.QApplication.translate("Frame", "Estimate posterior distributions of parameters and model checking", None, QtGui.QApplication.UnicodeUTF8))
        self.biasRadio.setText(QtGui.QApplication.translate("Frame", "Compute bias and precision on parameter estimations", None, QtGui.QApplication.UnicodeUTF8))
        self.comparisonRadio.setText(QtGui.QApplication.translate("Frame", "Compute posterior probabilities of scenarios", None, QtGui.QApplication.UnicodeUTF8))
        self.evaluateRadio.setText(QtGui.QApplication.translate("Frame", "Evaluate confidence in scenario choice", None, QtGui.QApplication.UnicodeUTF8))
        self.modCheckRadio.setText(QtGui.QApplication.translate("Frame", "Model checking", None, QtGui.QApplication.UnicodeUTF8))
        self.modCheckPcaCheck.setText(QtGui.QApplication.translate("Frame", "Principal Component Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.modCheckLossCheck.setText(QtGui.QApplication.translate("Frame", "Locate observed S.S among simulated S.S.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Analysis name : ", None, QtGui.QApplication.UnicodeUTF8))

