# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/diyabc.ui'
#
# Created: Mon Mar  7 17:54:31 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 750))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.page)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.accueilFrame = QtGui.QFrame(self.page_2)
        self.accueilFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.accueilFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.accueilFrame.setObjectName("accueilFrame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.accueilFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.imgLabel = QtGui.QLabel(self.accueilFrame)
        self.imgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout_4.addWidget(self.imgLabel)
        self.frame = QtGui.QFrame(self.accueilFrame)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.skipButton = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.skipButton.setFont(font)
        self.skipButton.setObjectName("skipButton")
        self.horizontalLayout.addWidget(self.skipButton)
        self.openButton = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.openButton.setFont(font)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.newButton = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.newButton.setFont(font)
        self.newButton.setObjectName("newButton")
        self.horizontalLayout.addWidget(self.newButton)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_5.addWidget(self.accueilFrame)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionWeb = QtGui.QAction(MainWindow)
        self.actionWeb.setCheckable(True)
        self.actionWeb.setObjectName("actionWeb")
        self.action = QtGui.QAction(MainWindow)
        self.action.setCheckable(True)
        self.action.setObjectName("action")
        self.actionLoop = QtGui.QAction(MainWindow)
        self.actionLoop.setCheckable(True)
        self.actionLoop.setObjectName("actionLoop")
        self.actionOngsuiv = QtGui.QAction(MainWindow)
        self.actionOngsuiv.setObjectName("actionOngsuiv")
        self.actionOngprec = QtGui.QAction(MainWindow)
        self.actionOngprec.setObjectName("actionOngprec")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.skipButton, self.openButton)
        MainWindow.setTabOrder(self.openButton, self.newButton)
        MainWindow.setTabOrder(self.newButton, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DIYABC", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Projet 2", None, QtGui.QApplication.UnicodeUTF8))
        self.imgLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.skipButton.setText(QtGui.QApplication.translate("MainWindow", "&Close this page", None, QtGui.QApplication.UnicodeUTF8))
        self.skipButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setText(QtGui.QApplication.translate("MainWindow", "&Open project", None, QtGui.QApplication.UnicodeUTF8))
        self.newButton.setText(QtGui.QApplication.translate("MainWindow", "&New project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWeb.setText(QtGui.QApplication.translate("MainWindow", "activer web", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWeb.setToolTip(QtGui.QApplication.translate("MainWindow", "obvious", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "plap", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setToolTip(QtGui.QApplication.translate("MainWindow", "hohoho", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoop.setText(QtGui.QApplication.translate("MainWindow", "loop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoop.setToolTip(QtGui.QApplication.translate("MainWindow", "c\'est la vie!", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoop.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOngsuiv.setText(QtGui.QApplication.translate("MainWindow", "ongsuiv", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOngsuiv.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+PgDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOngprec.setText(QtGui.QApplication.translate("MainWindow", "ongprec", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOngprec.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+PgUp", None, QtGui.QApplication.UnicodeUTF8))

