# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/drawScenarioFrame.ui'
#
# Created: Wed May 18 11:08:16 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(956, 660)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.printButton = QtGui.QPushButton(self.groupBox)
        self.printButton.setObjectName(_fromUtf8("printButton"))
        self.horizontalLayout.addWidget(self.printButton)
        self.savePicturesButton = QtGui.QPushButton(self.groupBox)
        self.savePicturesButton.setObjectName(_fromUtf8("savePicturesButton"))
        self.horizontalLayout.addWidget(self.savePicturesButton)
        self.ACProgress = QtGui.QProgressBar(self.groupBox)
        self.ACProgress.setProperty(_fromUtf8("value"), 24)
        self.ACProgress.setObjectName(_fromUtf8("ACProgress"))
        self.horizontalLayout.addWidget(self.ACProgress)
        self.viewLocateButton = QtGui.QPushButton(self.groupBox)
        self.viewLocateButton.setObjectName(_fromUtf8("viewLocateButton"))
        self.horizontalLayout.addWidget(self.viewLocateButton)
        spacerItem = QtGui.QSpacerItem(480, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.closeButton = QtGui.QPushButton(self.groupBox)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.PCAFrame = QtGui.QFrame(Frame)
        self.PCAFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.PCAFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.PCAFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.PCAFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.PCAFrame.setObjectName(_fromUtf8("PCAFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.PCAFrame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.PCAFrame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.PCAFrame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.PCAFrame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.scCombo = QtGui.QComboBox(self.PCAFrame)
        self.scCombo.setObjectName(_fromUtf8("scCombo"))
        self.gridLayout_2.addWidget(self.scCombo, 1, 0, 1, 1)
        self.compoHCombo = QtGui.QComboBox(self.PCAFrame)
        self.compoHCombo.setObjectName(_fromUtf8("compoHCombo"))
        self.gridLayout_2.addWidget(self.compoHCombo, 1, 1, 1, 1)
        self.nbpCombo = QtGui.QComboBox(self.PCAFrame)
        self.nbpCombo.setObjectName(_fromUtf8("nbpCombo"))
        self.nbpCombo.addItem(_fromUtf8(""))
        self.nbpCombo.addItem(_fromUtf8(""))
        self.nbpCombo.addItem(_fromUtf8(""))
        self.nbpCombo.addItem(_fromUtf8(""))
        self.nbpCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.nbpCombo, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.PCAFrame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.compoVCombo = QtGui.QComboBox(self.PCAFrame)
        self.compoVCombo.setObjectName(_fromUtf8("compoVCombo"))
        self.gridLayout_2.addWidget(self.compoVCombo, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.PCAFrame)
        self.scrollArea = QtGui.QScrollArea(Frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 930, 454))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.PCAGraphFrame = QtGui.QFrame(Frame)
        self.PCAGraphFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.PCAGraphFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.PCAGraphFrame.setObjectName(_fromUtf8("PCAGraphFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.PCAGraphFrame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout.addWidget(self.PCAGraphFrame)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.printButton.setText(QtGui.QApplication.translate("Frame", "PRINT", None, QtGui.QApplication.UnicodeUTF8))
        self.savePicturesButton.setText(QtGui.QApplication.translate("Frame", "SAVE", None, QtGui.QApplication.UnicodeUTF8))
        self.viewLocateButton.setText(QtGui.QApplication.translate("Frame", "View locate results", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("Frame", "CLOSE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Scenario to draw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Horizontal axis component", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Number of plots per scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.nbpCombo.setItemText(0, QtGui.QApplication.translate("Frame", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.nbpCombo.setItemText(1, QtGui.QApplication.translate("Frame", "2000", None, QtGui.QApplication.UnicodeUTF8))
        self.nbpCombo.setItemText(2, QtGui.QApplication.translate("Frame", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.nbpCombo.setItemText(3, QtGui.QApplication.translate("Frame", "10000", None, QtGui.QApplication.UnicodeUTF8))
        self.nbpCombo.setItemText(4, QtGui.QApplication.translate("Frame", "50000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "Vertical axis component", None, QtGui.QApplication.UnicodeUTF8))

