# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/setMutationModelSequences.ui'
#
# Created: Mon Apr  4 14:42:32 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(955, 685)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_28 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.frame_6 = QtGui.QFrame(Frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.exitButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.horizontalLayout_9.addWidget(self.exitButton)
        self.clearButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout_9.addWidget(self.clearButton)
        self.okButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okButton.setFont(font)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout_9.addWidget(self.okButton)
        self.verticalLayout_28.addWidget(self.frame_6)
        self.setMutSeqLabel = QtGui.QLabel(Frame)
        self.setMutSeqLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setMutSeqLabel.setFont(font)
        self.setMutSeqLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.setMutSeqLabel.setObjectName(_fromUtf8("setMutSeqLabel"))
        self.verticalLayout_28.addWidget(self.setMutSeqLabel)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.frame = QtGui.QFrame(Frame)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.firstFrame = QtGui.QFrame(self.frame)
        self.firstFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.firstFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.firstFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.firstFrame.setObjectName(_fromUtf8("firstFrame"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.firstFrame)
        self.horizontalLayout_7.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.mmrLabel = QtGui.QLabel(self.firstFrame)
        self.mmrLabel.setMinimumSize(QtCore.QSize(130, 0))
        self.mmrLabel.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mmrLabel.setFont(font)
        self.mmrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mmrLabel.setObjectName(_fromUtf8("mmrLabel"))
        self.horizontalLayout_7.addWidget(self.mmrLabel)
        self.groupBox_4 = QtGui.QGroupBox(self.firstFrame)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.mmrUnifRadio = QtGui.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mmrUnifRadio.setFont(font)
        self.mmrUnifRadio.setChecked(True)
        self.mmrUnifRadio.setObjectName(_fromUtf8("mmrUnifRadio"))
        self.horizontalLayout_8.addWidget(self.mmrUnifRadio)
        self.mmrLogRadio = QtGui.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mmrLogRadio.setFont(font)
        self.mmrLogRadio.setChecked(False)
        self.mmrLogRadio.setObjectName(_fromUtf8("mmrLogRadio"))
        self.horizontalLayout_8.addWidget(self.mmrLogRadio)
        self.mmrGammaRadio = QtGui.QRadioButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mmrGammaRadio.setFont(font)
        self.mmrGammaRadio.setObjectName(_fromUtf8("mmrGammaRadio"))
        self.horizontalLayout_8.addWidget(self.mmrGammaRadio)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_19 = QtGui.QLabel(self.firstFrame)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_14.addWidget(self.label_19)
        self.mmrMinEdit = QtGui.QLineEdit(self.firstFrame)
        self.mmrMinEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mmrMinEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mmrMinEdit.setObjectName(_fromUtf8("mmrMinEdit"))
        self.verticalLayout_14.addWidget(self.mmrMinEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_20 = QtGui.QLabel(self.firstFrame)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_15.addWidget(self.label_20)
        self.mmrMaxEdit = QtGui.QLineEdit(self.firstFrame)
        self.mmrMaxEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mmrMaxEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mmrMaxEdit.setObjectName(_fromUtf8("mmrMaxEdit"))
        self.verticalLayout_15.addWidget(self.mmrMaxEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_21 = QtGui.QLabel(self.firstFrame)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_16.addWidget(self.label_21)
        self.mmrMeanEdit = QtGui.QLineEdit(self.firstFrame)
        self.mmrMeanEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mmrMeanEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mmrMeanEdit.setObjectName(_fromUtf8("mmrMeanEdit"))
        self.verticalLayout_16.addWidget(self.mmrMeanEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_22 = QtGui.QLabel(self.firstFrame)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_17.addWidget(self.label_22)
        self.mmrShapeEdit = QtGui.QLineEdit(self.firstFrame)
        self.mmrShapeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mmrShapeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mmrShapeEdit.setObjectName(_fromUtf8("mmrShapeEdit"))
        self.verticalLayout_17.addWidget(self.mmrShapeEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.verticalLayout_26.addWidget(self.firstFrame)
        self.secondFrame = QtGui.QFrame(self.frame)
        self.secondFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.secondFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.secondFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.secondFrame.setObjectName(_fromUtf8("secondFrame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.secondFrame)
        self.horizontalLayout_5.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ilmrLabel = QtGui.QLabel(self.secondFrame)
        self.ilmrLabel.setMinimumSize(QtCore.QSize(130, 0))
        self.ilmrLabel.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ilmrLabel.setFont(font)
        self.ilmrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ilmrLabel.setObjectName(_fromUtf8("ilmrLabel"))
        self.horizontalLayout_5.addWidget(self.ilmrLabel)
        self.groupBox_3 = QtGui.QGroupBox(self.secondFrame)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.horizontalLayout_6.addWidget(self.radioButton_9)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_14 = QtGui.QLabel(self.secondFrame)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_10.addWidget(self.label_14)
        self.ilmrMinEdit = QtGui.QLineEdit(self.secondFrame)
        self.ilmrMinEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilmrMinEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilmrMinEdit.setObjectName(_fromUtf8("ilmrMinEdit"))
        self.verticalLayout_10.addWidget(self.ilmrMinEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_15 = QtGui.QLabel(self.secondFrame)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_11.addWidget(self.label_15)
        self.ilmrMaxEdit = QtGui.QLineEdit(self.secondFrame)
        self.ilmrMaxEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilmrMaxEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilmrMaxEdit.setObjectName(_fromUtf8("ilmrMaxEdit"))
        self.verticalLayout_11.addWidget(self.ilmrMaxEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_16 = QtGui.QLabel(self.secondFrame)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_12.addWidget(self.label_16)
        self.ilmrMeanEdit = QtGui.QLineEdit(self.secondFrame)
        self.ilmrMeanEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilmrMeanEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilmrMeanEdit.setReadOnly(True)
        self.ilmrMeanEdit.setObjectName(_fromUtf8("ilmrMeanEdit"))
        self.verticalLayout_12.addWidget(self.ilmrMeanEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_17 = QtGui.QLabel(self.secondFrame)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_13.addWidget(self.label_17)
        self.ilmrShapeEdit = QtGui.QLineEdit(self.secondFrame)
        self.ilmrShapeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilmrShapeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilmrShapeEdit.setObjectName(_fromUtf8("ilmrShapeEdit"))
        self.verticalLayout_13.addWidget(self.ilmrShapeEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_26.addWidget(self.secondFrame)
        self.thirdFrame = QtGui.QFrame(self.frame)
        self.thirdFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.thirdFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.thirdFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.thirdFrame.setObjectName(_fromUtf8("thirdFrame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.thirdFrame)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mc1Label = QtGui.QLabel(self.thirdFrame)
        self.mc1Label.setMinimumSize(QtCore.QSize(130, 0))
        self.mc1Label.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mc1Label.setFont(font)
        self.mc1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.mc1Label.setObjectName(_fromUtf8("mc1Label"))
        self.horizontalLayout_2.addWidget(self.mc1Label)
        self.groupBox = QtGui.QGroupBox(self.thirdFrame)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mc1UnifRadio = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mc1UnifRadio.setFont(font)
        self.mc1UnifRadio.setChecked(True)
        self.mc1UnifRadio.setObjectName(_fromUtf8("mc1UnifRadio"))
        self.horizontalLayout.addWidget(self.mc1UnifRadio)
        self.mc1LogRadio = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mc1LogRadio.setFont(font)
        self.mc1LogRadio.setObjectName(_fromUtf8("mc1LogRadio"))
        self.horizontalLayout.addWidget(self.mc1LogRadio)
        self.mc1GammaRadio = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mc1GammaRadio.setFont(font)
        self.mc1GammaRadio.setObjectName(_fromUtf8("mc1GammaRadio"))
        self.horizontalLayout.addWidget(self.mc1GammaRadio)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(self.thirdFrame)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.mc1MinEdit = QtGui.QLineEdit(self.thirdFrame)
        self.mc1MinEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mc1MinEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mc1MinEdit.setObjectName(_fromUtf8("mc1MinEdit"))
        self.verticalLayout.addWidget(self.mc1MinEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(self.thirdFrame)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.mc1MaxEdit = QtGui.QLineEdit(self.thirdFrame)
        self.mc1MaxEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mc1MaxEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mc1MaxEdit.setObjectName(_fromUtf8("mc1MaxEdit"))
        self.verticalLayout_2.addWidget(self.mc1MaxEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.thirdFrame)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.mc1MeanEdit = QtGui.QLineEdit(self.thirdFrame)
        self.mc1MeanEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mc1MeanEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mc1MeanEdit.setObjectName(_fromUtf8("mc1MeanEdit"))
        self.verticalLayout_3.addWidget(self.mc1MeanEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.thirdFrame)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.mc1ShapeEdit = QtGui.QLineEdit(self.thirdFrame)
        self.mc1ShapeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mc1ShapeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mc1ShapeEdit.setObjectName(_fromUtf8("mc1ShapeEdit"))
        self.verticalLayout_4.addWidget(self.mc1ShapeEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_26.addWidget(self.thirdFrame)
        self.fourthFrame = QtGui.QFrame(self.frame)
        self.fourthFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fourthFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fourthFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fourthFrame.setObjectName(_fromUtf8("fourthFrame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.fourthFrame)
        self.horizontalLayout_3.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ilc1Label = QtGui.QLabel(self.fourthFrame)
        self.ilc1Label.setMinimumSize(QtCore.QSize(130, 0))
        self.ilc1Label.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ilc1Label.setFont(font)
        self.ilc1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc1Label.setObjectName(_fromUtf8("ilc1Label"))
        self.horizontalLayout_3.addWidget(self.ilc1Label)
        self.groupBox_2 = QtGui.QGroupBox(self.fourthFrame)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.horizontalLayout_4.addWidget(self.radioButton_6)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_9 = QtGui.QLabel(self.fourthFrame)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_5.addWidget(self.label_9)
        self.ilc1MinEdit = QtGui.QLineEdit(self.fourthFrame)
        self.ilc1MinEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilc1MinEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc1MinEdit.setObjectName(_fromUtf8("ilc1MinEdit"))
        self.verticalLayout_5.addWidget(self.ilc1MinEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_10 = QtGui.QLabel(self.fourthFrame)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_7.addWidget(self.label_10)
        self.ilc1MaxEdit = QtGui.QLineEdit(self.fourthFrame)
        self.ilc1MaxEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilc1MaxEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc1MaxEdit.setObjectName(_fromUtf8("ilc1MaxEdit"))
        self.verticalLayout_7.addWidget(self.ilc1MaxEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_11 = QtGui.QLabel(self.fourthFrame)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_8.addWidget(self.label_11)
        self.ilc1MeanEdit = QtGui.QLineEdit(self.fourthFrame)
        self.ilc1MeanEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilc1MeanEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc1MeanEdit.setObjectName(_fromUtf8("ilc1MeanEdit"))
        self.verticalLayout_8.addWidget(self.ilc1MeanEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_12 = QtGui.QLabel(self.fourthFrame)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_9.addWidget(self.label_12)
        self.ilc1ShapeEdit = QtGui.QLineEdit(self.fourthFrame)
        self.ilc1ShapeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilc1ShapeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc1ShapeEdit.setObjectName(_fromUtf8("ilc1ShapeEdit"))
        self.verticalLayout_9.addWidget(self.ilc1ShapeEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_26.addWidget(self.fourthFrame)
        self.fifthFrame = QtGui.QFrame(self.frame)
        self.fifthFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fifthFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fifthFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fifthFrame.setObjectName(_fromUtf8("fifthFrame"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.fifthFrame)
        self.horizontalLayout_10.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.mc2Label = QtGui.QLabel(self.fifthFrame)
        self.mc2Label.setMinimumSize(QtCore.QSize(130, 0))
        self.mc2Label.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mc2Label.setFont(font)
        self.mc2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.mc2Label.setObjectName(_fromUtf8("mc2Label"))
        self.horizontalLayout_10.addWidget(self.mc2Label)
        self.groupBox_5 = QtGui.QGroupBox(self.fifthFrame)
        self.groupBox_5.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.mc2UnifRadio = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mc2UnifRadio.setFont(font)
        self.mc2UnifRadio.setChecked(True)
        self.mc2UnifRadio.setObjectName(_fromUtf8("mc2UnifRadio"))
        self.horizontalLayout_11.addWidget(self.mc2UnifRadio)
        self.mc2LogRadio = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mc2LogRadio.setFont(font)
        self.mc2LogRadio.setChecked(False)
        self.mc2LogRadio.setObjectName(_fromUtf8("mc2LogRadio"))
        self.horizontalLayout_11.addWidget(self.mc2LogRadio)
        self.mc2GammaRadio = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mc2GammaRadio.setFont(font)
        self.mc2GammaRadio.setObjectName(_fromUtf8("mc2GammaRadio"))
        self.horizontalLayout_11.addWidget(self.mc2GammaRadio)
        self.horizontalLayout_10.addWidget(self.groupBox_5)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_24 = QtGui.QLabel(self.fifthFrame)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_18.addWidget(self.label_24)
        self.mc2MinEdit = QtGui.QLineEdit(self.fifthFrame)
        self.mc2MinEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mc2MinEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mc2MinEdit.setObjectName(_fromUtf8("mc2MinEdit"))
        self.verticalLayout_18.addWidget(self.mc2MinEdit)
        self.horizontalLayout_10.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_25 = QtGui.QLabel(self.fifthFrame)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_19.addWidget(self.label_25)
        self.mc2MaxEdit = QtGui.QLineEdit(self.fifthFrame)
        self.mc2MaxEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mc2MaxEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mc2MaxEdit.setObjectName(_fromUtf8("mc2MaxEdit"))
        self.verticalLayout_19.addWidget(self.mc2MaxEdit)
        self.horizontalLayout_10.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_26 = QtGui.QLabel(self.fifthFrame)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_20.addWidget(self.label_26)
        self.mc2MeanEdit = QtGui.QLineEdit(self.fifthFrame)
        self.mc2MeanEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mc2MeanEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mc2MeanEdit.setObjectName(_fromUtf8("mc2MeanEdit"))
        self.verticalLayout_20.addWidget(self.mc2MeanEdit)
        self.horizontalLayout_10.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_27 = QtGui.QLabel(self.fifthFrame)
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_21.addWidget(self.label_27)
        self.mc2ShapeEdit = QtGui.QLineEdit(self.fifthFrame)
        self.mc2ShapeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mc2ShapeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mc2ShapeEdit.setObjectName(_fromUtf8("mc2ShapeEdit"))
        self.verticalLayout_21.addWidget(self.mc2ShapeEdit)
        self.horizontalLayout_10.addLayout(self.verticalLayout_21)
        self.verticalLayout_26.addWidget(self.fifthFrame)
        self.sixthFrame = QtGui.QFrame(self.frame)
        self.sixthFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.sixthFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sixthFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sixthFrame.setObjectName(_fromUtf8("sixthFrame"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.sixthFrame)
        self.horizontalLayout_12.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.ilc2Label = QtGui.QLabel(self.sixthFrame)
        self.ilc2Label.setMinimumSize(QtCore.QSize(130, 0))
        self.ilc2Label.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ilc2Label.setFont(font)
        self.ilc2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc2Label.setObjectName(_fromUtf8("ilc2Label"))
        self.horizontalLayout_12.addWidget(self.ilc2Label)
        self.groupBox_6 = QtGui.QGroupBox(self.sixthFrame)
        self.groupBox_6.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_13.setSpacing(1)
        self.horizontalLayout_13.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.radioButton_18 = QtGui.QRadioButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_18.setFont(font)
        self.radioButton_18.setChecked(True)
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.horizontalLayout_13.addWidget(self.radioButton_18)
        self.horizontalLayout_12.addWidget(self.groupBox_6)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.label_29 = QtGui.QLabel(self.sixthFrame)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_22.addWidget(self.label_29)
        self.ilc2MinEdit = QtGui.QLineEdit(self.sixthFrame)
        self.ilc2MinEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilc2MinEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc2MinEdit.setObjectName(_fromUtf8("ilc2MinEdit"))
        self.verticalLayout_22.addWidget(self.ilc2MinEdit)
        self.horizontalLayout_12.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_30 = QtGui.QLabel(self.sixthFrame)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_23.addWidget(self.label_30)
        self.ilc2MaxEdit = QtGui.QLineEdit(self.sixthFrame)
        self.ilc2MaxEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilc2MaxEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc2MaxEdit.setObjectName(_fromUtf8("ilc2MaxEdit"))
        self.verticalLayout_23.addWidget(self.ilc2MaxEdit)
        self.horizontalLayout_12.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.label_31 = QtGui.QLabel(self.sixthFrame)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_24.addWidget(self.label_31)
        self.ilc2MeanEdit = QtGui.QLineEdit(self.sixthFrame)
        self.ilc2MeanEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilc2MeanEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc2MeanEdit.setObjectName(_fromUtf8("ilc2MeanEdit"))
        self.verticalLayout_24.addWidget(self.ilc2MeanEdit)
        self.horizontalLayout_12.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.label_32 = QtGui.QLabel(self.sixthFrame)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_25.addWidget(self.label_32)
        self.ilc2ShapeEdit = QtGui.QLineEdit(self.sixthFrame)
        self.ilc2ShapeEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ilc2ShapeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ilc2ShapeEdit.setObjectName(_fromUtf8("ilc2ShapeEdit"))
        self.verticalLayout_25.addWidget(self.ilc2ShapeEdit)
        self.horizontalLayout_12.addLayout(self.verticalLayout_25)
        self.verticalLayout_26.addWidget(self.sixthFrame)
        self.label_35 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_26.addWidget(self.label_35)
        self.horizontalLayout_14.addWidget(self.frame)
        self.frame_9 = QtGui.QFrame(Frame)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.groupBox_7 = QtGui.QGroupBox(self.frame_9)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.jukesRadio = QtGui.QRadioButton(self.groupBox_7)
        self.jukesRadio.setChecked(False)
        self.jukesRadio.setObjectName(_fromUtf8("jukesRadio"))
        self.verticalLayout_6.addWidget(self.jukesRadio)
        self.kimuraRadio = QtGui.QRadioButton(self.groupBox_7)
        self.kimuraRadio.setChecked(True)
        self.kimuraRadio.setObjectName(_fromUtf8("kimuraRadio"))
        self.verticalLayout_6.addWidget(self.kimuraRadio)
        self.haseRadio = QtGui.QRadioButton(self.groupBox_7)
        self.haseRadio.setObjectName(_fromUtf8("haseRadio"))
        self.verticalLayout_6.addWidget(self.haseRadio)
        self.tamuraRadio = QtGui.QRadioButton(self.groupBox_7)
        self.tamuraRadio.setObjectName(_fromUtf8("tamuraRadio"))
        self.verticalLayout_6.addWidget(self.tamuraRadio)
        self.verticalLayout_27.addWidget(self.groupBox_7)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.frame_9)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.isEdit = QtGui.QLineEdit(self.frame_9)
        self.isEdit.setObjectName(_fromUtf8("isEdit"))
        self.gridLayout.addWidget(self.isEdit, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.frame_9)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.sotgEdit = QtGui.QLineEdit(self.frame_9)
        self.sotgEdit.setObjectName(_fromUtf8("sotgEdit"))
        self.gridLayout.addWidget(self.sotgEdit, 1, 2, 1, 1)
        self.verticalLayout_27.addLayout(self.gridLayout)
        self.horizontalLayout_14.addWidget(self.frame_9)
        self.verticalLayout_28.addLayout(self.horizontalLayout_14)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setToolTip(QtGui.QApplication.translate("Frame", "Leave this screen without loosing any change", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("Frame", "EXIT", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setToolTip(QtGui.QApplication.translate("Frame", "Clear all data related to this historical model", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("Frame", "CLEAR", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("Frame", "Test and save data (Alt+o)", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Frame", "VALIDATE", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+V", None, QtGui.QApplication.UnicodeUTF8))
        self.setMutSeqLabel.setText(QtGui.QApplication.translate("Frame", "Set mutation Model (Sequences)", None, QtGui.QApplication.UnicodeUTF8))
        self.mmrLabel.setText(QtGui.QApplication.translate("Frame", "Mean mutation\n"
"rate (per site\n"
"per generation)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.mmrUnifRadio.setText(QtGui.QApplication.translate("Frame", "Unif", None, QtGui.QApplication.UnicodeUTF8))
        self.mmrLogRadio.setText(QtGui.QApplication.translate("Frame", "Log-u", None, QtGui.QApplication.UnicodeUTF8))
        self.mmrGammaRadio.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.mmrMinEdit.setText(QtGui.QApplication.translate("Frame", "1.00E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.mmrMaxEdit.setText(QtGui.QApplication.translate("Frame", "1.00E-7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.mmrMeanEdit.setText(QtGui.QApplication.translate("Frame", "5E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Frame", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.mmrShapeEdit.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.ilmrLabel.setText(QtGui.QApplication.translate("Frame", "Individuals locus\n"
"mutation rate\n"
"(Gamma distribution\n"
"around mean)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_9.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.ilmrMinEdit.setText(QtGui.QApplication.translate("Frame", "1.00E-9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.ilmrMaxEdit.setText(QtGui.QApplication.translate("Frame", "1.00E-6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.ilmrMeanEdit.setText(QtGui.QApplication.translate("Frame", "Mean_µ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Frame", "Shape (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.ilmrShapeEdit.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.mc1Label.setText(QtGui.QApplication.translate("Frame", "Mean\n"
"coefficient\n"
"k_C/T", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.mc1UnifRadio.setText(QtGui.QApplication.translate("Frame", "Unif", None, QtGui.QApplication.UnicodeUTF8))
        self.mc1LogRadio.setText(QtGui.QApplication.translate("Frame", "Log-u", None, QtGui.QApplication.UnicodeUTF8))
        self.mc1GammaRadio.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.mc1MinEdit.setText(QtGui.QApplication.translate("Frame", "0.050", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.mc1MaxEdit.setText(QtGui.QApplication.translate("Frame", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.mc1MeanEdit.setText(QtGui.QApplication.translate("Frame", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.mc1ShapeEdit.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc1Label.setText(QtGui.QApplication.translate("Frame", "Individuals locus\n"
"coefficient k_C/T\n"
"(Gamma distribution\n"
"around mean)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc1MinEdit.setText(QtGui.QApplication.translate("Frame", "0.050", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc1MaxEdit.setText(QtGui.QApplication.translate("Frame", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc1MeanEdit.setText(QtGui.QApplication.translate("Frame", "Mean_k1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Frame", "Shape (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc1ShapeEdit.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.mc2Label.setText(QtGui.QApplication.translate("Frame", "Mean coefficient\n"
"k_A/G", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.mc2UnifRadio.setText(QtGui.QApplication.translate("Frame", "Unif", None, QtGui.QApplication.UnicodeUTF8))
        self.mc2LogRadio.setText(QtGui.QApplication.translate("Frame", "Log-u", None, QtGui.QApplication.UnicodeUTF8))
        self.mc2GammaRadio.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.mc2MinEdit.setText(QtGui.QApplication.translate("Frame", "0.050", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.mc2MaxEdit.setText(QtGui.QApplication.translate("Frame", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.mc2MeanEdit.setText(QtGui.QApplication.translate("Frame", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Frame", "Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.mc2ShapeEdit.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc2Label.setText(QtGui.QApplication.translate("Frame", "Individuals locus\n"
"coefficient k_A/G\n"
"(Gamma distribution\n"
"around mean)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Frame", "Prior distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_18.setText(QtGui.QApplication.translate("Frame", "Gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Frame", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc2MinEdit.setText(QtGui.QApplication.translate("Frame", "0.050", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Frame", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc2MaxEdit.setText(QtGui.QApplication.translate("Frame", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Frame", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc2MeanEdit.setText(QtGui.QApplication.translate("Frame", "Mean_k2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Frame", "Shape (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.ilc2ShapeEdit.setText(QtGui.QApplication.translate("Frame", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Frame", "(1) Set the shape to 0 if you want all individuals loci to take the same value (=mean)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Frame", "Mutation model", None, QtGui.QApplication.UnicodeUTF8))
        self.jukesRadio.setText(QtGui.QApplication.translate("Frame", "Jukes Kantor (1969)", None, QtGui.QApplication.UnicodeUTF8))
        self.kimuraRadio.setText(QtGui.QApplication.translate("Frame", "Kimura 2 Parameters (1980)", None, QtGui.QApplication.UnicodeUTF8))
        self.haseRadio.setText(QtGui.QApplication.translate("Frame", "Hasegawa-Kishino-Yano (1985)", None, QtGui.QApplication.UnicodeUTF8))
        self.tamuraRadio.setText(QtGui.QApplication.translate("Frame", "Tamura Nei (1993)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "% of invariant sites :", None, QtGui.QApplication.UnicodeUTF8))
        self.isEdit.setText(QtGui.QApplication.translate("Frame", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Shape of the gamma :", None, QtGui.QApplication.UnicodeUTF8))
        self.sotgEdit.setText(QtGui.QApplication.translate("Frame", "2.00", None, QtGui.QApplication.UnicodeUTF8))

