# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/setupEstimationBias.ui'
#
# Created: Mon Apr  4 18:05:50 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(779, 633)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_6 = QtGui.QFrame(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.exitButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.horizontalLayout_9.addWidget(self.exitButton)
        self.okButton = QtGui.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okButton.setFont(font)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout_9.addWidget(self.okButton)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.label = QtGui.QLabel(Frame)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(Frame)
        self.label_6.setMinimumSize(QtCore.QSize(130, 0))
        self.label_6.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.projectNameEdit = QtGui.QLineEdit(Frame)
        self.projectNameEdit.setReadOnly(True)
        self.projectNameEdit.setObjectName(_fromUtf8("projectNameEdit"))
        self.horizontalLayout_7.addWidget(self.projectNameEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.scenariosLabel = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenariosLabel.sizePolicy().hasHeightForWidth())
        self.scenariosLabel.setSizePolicy(sizePolicy)
        self.scenariosLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.scenariosLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scenariosLabel.setFont(font)
        self.scenariosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scenariosLabel.setObjectName(_fromUtf8("scenariosLabel"))
        self.horizontalLayout_4.addWidget(self.scenariosLabel)
        self.redefButton = QtGui.QPushButton(Frame)
        self.redefButton.setMinimumSize(QtCore.QSize(100, 0))
        self.redefButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.redefButton.setObjectName(_fromUtf8("redefButton"))
        self.horizontalLayout_4.addWidget(self.redefButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.candidateLabel = QtGui.QLabel(Frame)
        self.candidateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.candidateLabel.setObjectName(_fromUtf8("candidateLabel"))
        self.horizontalLayout_6.addWidget(self.candidateLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 13))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 13))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.notdsEdit = QtGui.QLineEdit(Frame)
        self.notdsEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.notdsEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.notdsEdit.setObjectName(_fromUtf8("notdsEdit"))
        self.horizontalLayout_5.addWidget(self.notdsEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 13))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.nosdEdit = QtGui.QLineEdit(Frame)
        self.nosdEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.nosdEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nosdEdit.setObjectName(_fromUtf8("nosdEdit"))
        self.gridLayout_2.addWidget(self.nosdEdit, 0, 1, 2, 1)
        self.label_3 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 13))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.groupBox_2 = QtGui.QGroupBox(Frame)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.noRadio = QtGui.QRadioButton(self.groupBox_2)
        self.noRadio.setObjectName(_fromUtf8("noRadio"))
        self.horizontalLayout_2.addWidget(self.noRadio)
        self.logRadio = QtGui.QRadioButton(self.groupBox_2)
        self.logRadio.setObjectName(_fromUtf8("logRadio"))
        self.horizontalLayout_2.addWidget(self.logRadio)
        self.logitRadio = QtGui.QRadioButton(self.groupBox_2)
        self.logitRadio.setChecked(True)
        self.logitRadio.setObjectName(_fromUtf8("logitRadio"))
        self.horizontalLayout_2.addWidget(self.logitRadio)
        self.logtgRadio = QtGui.QRadioButton(self.groupBox_2)
        self.logtgRadio.setObjectName(_fromUtf8("logtgRadio"))
        self.horizontalLayout_2.addWidget(self.logtgRadio)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(Frame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(Frame)
        self.label_7.setMinimumSize(QtCore.QSize(220, 0))
        self.label_7.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 3)
        self.label_8 = QtGui.QLabel(Frame)
        self.label_8.setMinimumSize(QtCore.QSize(220, 0))
        self.label_8.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 3)
        self.totNumSimEdit = QtGui.QLineEdit(Frame)
        self.totNumSimEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.totNumSimEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.totNumSimEdit.setReadOnly(True)
        self.totNumSimEdit.setObjectName(_fromUtf8("totNumSimEdit"))
        self.gridLayout.addWidget(self.totNumSimEdit, 3, 3, 1, 1)
        self.cnosdEdit = QtGui.QLineEdit(Frame)
        self.cnosdEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.cnosdEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cnosdEdit.setObjectName(_fromUtf8("cnosdEdit"))
        self.gridLayout.addWidget(self.cnosdEdit, 4, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.redefSumStatsFrame = QtGui.QFrame(Frame)
        self.redefSumStatsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.redefSumStatsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.redefSumStatsFrame.setObjectName(_fromUtf8("redefSumStatsFrame"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.redefSumStatsFrame)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.redefSumStatsButton = QtGui.QPushButton(self.redefSumStatsFrame)
        self.redefSumStatsButton.setObjectName(_fromUtf8("redefSumStatsButton"))
        self.horizontalLayout_8.addWidget(self.redefSumStatsButton)
        self.redefSumStatsCombo = QtGui.QComboBox(self.redefSumStatsFrame)
        self.redefSumStatsCombo.setObjectName(_fromUtf8("redefSumStatsCombo"))
        self.horizontalLayout_8.addWidget(self.redefSumStatsCombo)
        self.verticalLayout_2.addWidget(self.redefSumStatsFrame)
        self.paramChoiceBox = QtGui.QGroupBox(Frame)
        self.paramChoiceBox.setObjectName(_fromUtf8("paramChoiceBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.paramChoiceBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.oCheck = QtGui.QCheckBox(self.paramChoiceBox)
        self.oCheck.setChecked(True)
        self.oCheck.setObjectName(_fromUtf8("oCheck"))
        self.horizontalLayout.addWidget(self.oCheck)
        self.cCheck = QtGui.QCheckBox(self.paramChoiceBox)
        self.cCheck.setChecked(True)
        self.cCheck.setObjectName(_fromUtf8("cCheck"))
        self.horizontalLayout.addWidget(self.cCheck)
        self.verticalLayout_2.addWidget(self.paramChoiceBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setToolTip(QtGui.QApplication.translate("Frame", "Leave this screen without loosing any change", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("Frame", "CANCEL", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+E", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("Frame", "Test and save data (Alt+o)", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("Frame", "VALIDATE", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setShortcut(QtGui.QApplication.translate("Frame", "Alt+V", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "ABC parameter estimation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Project directory : ", None, QtGui.QApplication.UnicodeUTF8))
        self.scenariosLabel.setText(QtGui.QApplication.translate("Frame", "Chosen scenario :", None, QtGui.QApplication.UnicodeUTF8))
        self.redefButton.setText(QtGui.QApplication.translate("Frame", "Redefine", None, QtGui.QApplication.UnicodeUTF8))
        self.candidateLabel.setText(QtGui.QApplication.translate("Frame", "Candidate scenarios : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Number of test data sets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Data sets simulated with know parameter values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Number of selected data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "(simulated data closest to observed)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Frame", "Transformation of parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.noRadio.setText(QtGui.QApplication.translate("Frame", "no", None, QtGui.QApplication.UnicodeUTF8))
        self.logRadio.setText(QtGui.QApplication.translate("Frame", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.logitRadio.setText(QtGui.QApplication.translate("Frame", "logit", None, QtGui.QApplication.UnicodeUTF8))
        self.logtgRadio.setText(QtGui.QApplication.translate("Frame", "log-tg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "Total number of simulated data\n"
"in the reference table :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "Chosen number of simulated data : ", None, QtGui.QApplication.UnicodeUTF8))
        self.redefSumStatsButton.setText(QtGui.QApplication.translate("Frame", "Redefine summary statistics of group :", None, QtGui.QApplication.UnicodeUTF8))
        self.paramChoiceBox.setTitle(QtGui.QApplication.translate("Frame", "Choice of parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.oCheck.setText(QtGui.QApplication.translate("Frame", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.cCheck.setText(QtGui.QApplication.translate("Frame", "Composite", None, QtGui.QApplication.UnicodeUTF8))

